--Name : ToolTipController.lua
--Author : generated by FairyGUI
--Date : 2020-6-28
--Desc : 

local ToolTipController = class("ToolTipController",Controller)

function ToolTipController:init()
	
end

return ToolTipController