--Name : commonModel.lua
--Author : generated by FairyGUI
--Date : 2020-3-4
--Desc : 


local commonModel = class("commonModel", BaseModel)

function commonModel:ctor()

end

function commonModel:init()

end


return commonModel
