--This file is auto transformed from excel sheet file by script. 
--You **should NOT** edit it manually.
--Copyright @Guangyv Games 2016.

return {
 {   scoreDiffLower = -999999,   scoreDiffUpper = -600,   winScore = 30,   loseScore = -1, 
 }, 
 {   scoreDiffLower = -600,   scoreDiffUpper = -500,   winScore = 29,   loseScore = -2, 
 }, 
 {   scoreDiffLower = -500,   scoreDiffUpper = -400,   winScore = 28,   loseScore = -3, 
 }, 
 {   scoreDiffLower = -400,   scoreDiffUpper = -350,   winScore = 27,   loseScore = -4, 
 }, 
 {   scoreDiffLower = -350,   scoreDiffUpper = -300,   winScore = 26,   loseScore = -5, 
 }, 
 {   scoreDiffLower = -300,   scoreDiffUpper = -250,   winScore = 25,   loseScore = -6, 
 }, 
 {   scoreDiffLower = -250,   scoreDiffUpper = -200,   winScore = 24,   loseScore = -7, 
 }, 
 {   scoreDiffLower = -200,   scoreDiffUpper = -175,   winScore = 23,   loseScore = -8, 
 }, 
 {   scoreDiffLower = -175,   scoreDiffUpper = -150,   winScore = 22,   loseScore = -9, 
 }, 
 {   scoreDiffLower = -175,   scoreDiffUpper = -125,   winScore = 21,   loseScore = -10, 
 }, 
 {   scoreDiffLower = -150,   scoreDiffUpper = -100,   winScore = 20,   loseScore = -11, 
 }, 
 {   scoreDiffLower = -100,   scoreDiffUpper = -75,   winScore = 19,   loseScore = -12, 
 }, 
 {   scoreDiffLower = -75,   scoreDiffUpper = -50,   winScore = 18,   loseScore = -13, 
 }, 
 {   scoreDiffLower = -50,   scoreDiffUpper = -30,   winScore = 17,   loseScore = -14, 
 }, 
 {   scoreDiffLower = -30,   scoreDiffUpper = -10,   winScore = 16,   loseScore = -15, 
 }, 
 {   scoreDiffLower = -10,   scoreDiffUpper = 10,   winScore = 15,   loseScore = -16, 
 }, 
 {   scoreDiffLower = 10,   scoreDiffUpper = 30,   winScore = 14,   loseScore = -17, 
 }, 
 {   scoreDiffLower = 30,   scoreDiffUpper = 50,   winScore = 13,   loseScore = -18, 
 }, 
 {   scoreDiffLower = 50,   scoreDiffUpper = 75,   winScore = 12,   loseScore = -19, 
 }, 
 {   scoreDiffLower = 75,   scoreDiffUpper = 100,   winScore = 11,   loseScore = -20, 
 }, 
 {   scoreDiffLower = 100,   scoreDiffUpper = 125,   winScore = 10,   loseScore = -21, 
 }, 
 {   scoreDiffLower = 125,   scoreDiffUpper = 150,   winScore = 9,   loseScore = -22, 
 }, 
 {   scoreDiffLower = 150,   scoreDiffUpper = 175,   winScore = 8,   loseScore = -23, 
 }, 
 {   scoreDiffLower = 175,   scoreDiffUpper = 200,   winScore = 7,   loseScore = -24, 
 }, 
 {   scoreDiffLower = 200,   scoreDiffUpper = 250,   winScore = 6,   loseScore = -25, 
 }, 
 {   scoreDiffLower = 250,   scoreDiffUpper = 300,   winScore = 5,   loseScore = -26, 
 }, 
 {   scoreDiffLower = 300,   scoreDiffUpper = 350,   winScore = 4,   loseScore = -27, 
 }, 
 {   scoreDiffLower = 350,   scoreDiffUpper = 400,   winScore = 3,   loseScore = -28, 
 }, 
 {   scoreDiffLower = 400,   scoreDiffUpper = 500,   winScore = 2,   loseScore = -29, 
 }, 
 {   scoreDiffLower = 500,   scoreDiffUpper = 999999,   winScore = 1,   loseScore = -30, 
 }
}