--This file is auto transformed from excel sheet file by script. 
--You **should NOT** edit it manually.
--Copyright @Guangyv Games 2016.

-- Provinces.xls
-- Provinces
-- DynamicConfigData.t_provinces

return {
	[1] = {
		{id = 1,provinces = "北京",cityId = 1,city = "东城区"},
		{id = 1,provinces = "北京",cityId = 2,city = "西城区"},
		{id = 1,provinces = "北京",cityId = 3,city = "海淀区"},
		{id = 1,provinces = "北京",cityId = 4,city = "朝阳区"},
		{id = 1,provinces = "北京",cityId = 5,city = "丰台区"},
		{id = 1,provinces = "北京",cityId = 6,city = "石景山区"},
		{id = 1,provinces = "北京",cityId = 7,city = "通州区"},
		{id = 1,provinces = "北京",cityId = 8,city = "顺义区"},
		{id = 1,provinces = "北京",cityId = 9,city = "房山区"},
		{id = 1,provinces = "北京",cityId = 10,city = "大兴区"},
		{id = 1,provinces = "北京",cityId = 11,city = "昌平区"},
		{id = 1,provinces = "北京",cityId = 12,city = "怀柔区"},
		{id = 1,provinces = "北京",cityId = 13,city = "门头沟区"},
		{id = 1,provinces = "北京",cityId = 14,city = "平谷区"},
		{id = 1,provinces = "北京",cityId = 15,city = "密云县"},
		{id = 1,provinces = "北京",cityId = 16,city = "延庆县"},

	},
	[2] = {
		{id = 2,provinces = "天津",cityId = 1,city = "和平区"},
		{id = 2,provinces = "天津",cityId = 2,city = "河东区"},
		{id = 2,provinces = "天津",cityId = 3,city = "河西区"},
		{id = 2,provinces = "天津",cityId = 4,city = "南开区"},
		{id = 2,provinces = "天津",cityId = 5,city = "河北区"},
		{id = 2,provinces = "天津",cityId = 6,city = "红桥区"},
		{id = 2,provinces = "天津",cityId = 7,city = "滨海新区"},
		{id = 2,provinces = "天津",cityId = 8,city = "东丽区"},
		{id = 2,provinces = "天津",cityId = 9,city = "西青区"},
		{id = 2,provinces = "天津",cityId = 10,city = "津南区"},
		{id = 2,provinces = "天津",cityId = 11,city = "北辰区"},
		{id = 2,provinces = "天津",cityId = 12,city = "武清区"},
		{id = 2,provinces = "天津",cityId = 13,city = "宝坻区"},
		{id = 2,provinces = "天津",cityId = 14,city = "静海县"},
		{id = 2,provinces = "天津",cityId = 15,city = "宁河县"},
		{id = 2,provinces = "天津",cityId = 16,city = "蓟县"},

	},
	[3] = {
		{id = 3,provinces = "河北",cityId = 1,city = "石家庄市"},
		{id = 3,provinces = "河北",cityId = 2,city = "秦皇岛市"},
		{id = 3,provinces = "河北",cityId = 3,city = "张家口市"},
		{id = 3,provinces = "河北",cityId = 4,city = "保定市"},
		{id = 3,provinces = "河北",cityId = 5,city = "唐山市"},
		{id = 3,provinces = "河北",cityId = 6,city = "承德市"},
		{id = 3,provinces = "河北",cityId = 7,city = "廊坊市"},
		{id = 3,provinces = "河北",cityId = 8,city = "沧州市"},
		{id = 3,provinces = "河北",cityId = 9,city = "衡水市"},
		{id = 3,provinces = "河北",cityId = 10,city = "邢台市"},
		{id = 3,provinces = "河北",cityId = 11,city = "邯郸市"},

	},
	[4] = {
		{id = 4,provinces = "山西",cityId = 1,city = "太原市"},
		{id = 4,provinces = "山西",cityId = 2,city = "大同市"},
		{id = 4,provinces = "山西",cityId = 3,city = "阳泉市"},
		{id = 4,provinces = "山西",cityId = 4,city = "长治市"},
		{id = 4,provinces = "山西",cityId = 5,city = "晋城市"},
		{id = 4,provinces = "山西",cityId = 6,city = "朔州市"},
		{id = 4,provinces = "山西",cityId = 7,city = "晋中市"},
		{id = 4,provinces = "山西",cityId = 8,city = "运城市"},
		{id = 4,provinces = "山西",cityId = 9,city = "忻州市"},
		{id = 4,provinces = "山西",cityId = 10,city = "临汾市"},
		{id = 4,provinces = "山西",cityId = 11,city = "吕梁市"},

	},
	[5] = {
		{id = 5,provinces = "内蒙古",cityId = 1,city = "呼和浩特市"},
		{id = 5,provinces = "内蒙古",cityId = 2,city = "包头市"},
		{id = 5,provinces = "内蒙古",cityId = 3,city = "乌海市"},
		{id = 5,provinces = "内蒙古",cityId = 4,city = "赤峰市"},
		{id = 5,provinces = "内蒙古",cityId = 5,city = "通辽市"},
		{id = 5,provinces = "内蒙古",cityId = 6,city = "鄂尔多斯市"},
		{id = 5,provinces = "内蒙古",cityId = 7,city = "呼伦贝尔市"},
		{id = 5,provinces = "内蒙古",cityId = 8,city = "巴彦淖尔市"},
		{id = 5,provinces = "内蒙古",cityId = 9,city = "乌兰察布市"},
		{id = 5,provinces = "内蒙古",cityId = 10,city = "兴安盟"},
		{id = 5,provinces = "内蒙古",cityId = 11,city = "锡林郭勒盟"},
		{id = 5,provinces = "内蒙古",cityId = 12,city = "阿拉善盟"},

	},
	[6] = {
		{id = 6,provinces = "辽宁",cityId = 1,city = "沈阳市"},
		{id = 6,provinces = "辽宁",cityId = 2,city = "大连市"},
		{id = 6,provinces = "辽宁",cityId = 3,city = "鞍山市"},
		{id = 6,provinces = "辽宁",cityId = 4,city = "抚顺市"},
		{id = 6,provinces = "辽宁",cityId = 5,city = "本溪市"},
		{id = 6,provinces = "辽宁",cityId = 6,city = "丹东市"},
		{id = 6,provinces = "辽宁",cityId = 7,city = "锦州市"},
		{id = 6,provinces = "辽宁",cityId = 8,city = "营口市"},
		{id = 6,provinces = "辽宁",cityId = 9,city = "阜新市"},
		{id = 6,provinces = "辽宁",cityId = 10,city = "辽阳市"},
		{id = 6,provinces = "辽宁",cityId = 11,city = "盘锦市"},
		{id = 6,provinces = "辽宁",cityId = 12,city = "铁岭市"},
		{id = 6,provinces = "辽宁",cityId = 13,city = "朝阳市"},
		{id = 6,provinces = "辽宁",cityId = 14,city = "葫芦岛市"},

	},
	[7] = {
		{id = 7,provinces = "吉林",cityId = 1,city = "长春市"},
		{id = 7,provinces = "吉林",cityId = 2,city = "吉林市"},
		{id = 7,provinces = "吉林",cityId = 3,city = "四平市"},
		{id = 7,provinces = "吉林",cityId = 4,city = "辽源市"},
		{id = 7,provinces = "吉林",cityId = 5,city = "通化市"},
		{id = 7,provinces = "吉林",cityId = 6,city = "白山市"},
		{id = 7,provinces = "吉林",cityId = 7,city = "松原市"},
		{id = 7,provinces = "吉林",cityId = 8,city = "白城市"},
		{id = 7,provinces = "吉林",cityId = 9,city = "延边朝鲜族自治州"},

	},
	[8] = {
		{id = 8,provinces = "黑龙江",cityId = 1,city = "哈尔滨市"},
		{id = 8,provinces = "黑龙江",cityId = 2,city = "齐齐哈尔市"},
		{id = 8,provinces = "黑龙江",cityId = 3,city = "牡丹江市"},
		{id = 8,provinces = "黑龙江",cityId = 4,city = "佳木斯市"},
		{id = 8,provinces = "黑龙江",cityId = 5,city = "大庆市"},
		{id = 8,provinces = "黑龙江",cityId = 6,city = "鸡西市"},
		{id = 8,provinces = "黑龙江",cityId = 7,city = "双鸭山市"},
		{id = 8,provinces = "黑龙江",cityId = 8,city = "伊春市"},
		{id = 8,provinces = "黑龙江",cityId = 9,city = "七台河市"},
		{id = 8,provinces = "黑龙江",cityId = 10,city = "鹤岗市"},
		{id = 8,provinces = "黑龙江",cityId = 11,city = "黑河市"},
		{id = 8,provinces = "黑龙江",cityId = 12,city = "绥化市"},
		{id = 8,provinces = "黑龙江",cityId = 13,city = "大兴安岭地区"},

	},
	[9] = {
		{id = 9,provinces = "上海",cityId = 1,city = "黄浦区"},
		{id = 9,provinces = "上海",cityId = 2,city = "徐汇区"},
		{id = 9,provinces = "上海",cityId = 3,city = "长宁区"},
		{id = 9,provinces = "上海",cityId = 4,city = "静安区"},
		{id = 9,provinces = "上海",cityId = 5,city = "普陀区"},
		{id = 9,provinces = "上海",cityId = 6,city = "闸北区"},
		{id = 9,provinces = "上海",cityId = 7,city = "虹口区"},
		{id = 9,provinces = "上海",cityId = 8,city = "杨浦区"},
		{id = 9,provinces = "上海",cityId = 9,city = "浦东新区"},
		{id = 9,provinces = "上海",cityId = 10,city = "宝山区"},
		{id = 9,provinces = "上海",cityId = 11,city = "嘉定区"},
		{id = 9,provinces = "上海",cityId = 12,city = "青浦区"},
		{id = 9,provinces = "上海",cityId = 13,city = "松江区"},
		{id = 9,provinces = "上海",cityId = 14,city = "闵行区"},
		{id = 9,provinces = "上海",cityId = 15,city = "金山区"},
		{id = 9,provinces = "上海",cityId = 16,city = "奉贤区"},
		{id = 9,provinces = "上海",cityId = 17,city = "崇明县"},

	},
	[10] = {
		{id = 10,provinces = "江苏",cityId = 1,city = "南京市"},
		{id = 10,provinces = "江苏",cityId = 2,city = "无锡市"},
		{id = 10,provinces = "江苏",cityId = 3,city = "徐州市"},
		{id = 10,provinces = "江苏",cityId = 4,city = "常州市"},
		{id = 10,provinces = "江苏",cityId = 5,city = "苏州市"},
		{id = 10,provinces = "江苏",cityId = 6,city = "南通市"},
		{id = 10,provinces = "江苏",cityId = 7,city = "连云港市"},
		{id = 10,provinces = "江苏",cityId = 8,city = "淮安市"},
		{id = 10,provinces = "江苏",cityId = 9,city = "盐城市"},
		{id = 10,provinces = "江苏",cityId = 10,city = "扬州市"},
		{id = 10,provinces = "江苏",cityId = 11,city = "镇江市"},
		{id = 10,provinces = "江苏",cityId = 12,city = "泰州市"},
		{id = 10,provinces = "江苏",cityId = 13,city = "宿迁市"},

	},
	[11] = {
		{id = 11,provinces = "浙江",cityId = 1,city = "杭州市"},
		{id = 11,provinces = "浙江",cityId = 2,city = "宁波市"},
		{id = 11,provinces = "浙江",cityId = 3,city = "温州市"},
		{id = 11,provinces = "浙江",cityId = 4,city = "嘉兴市"},
		{id = 11,provinces = "浙江",cityId = 5,city = "湖州市"},
		{id = 11,provinces = "浙江",cityId = 6,city = "绍兴市"},
		{id = 11,provinces = "浙江",cityId = 7,city = "金华市"},
		{id = 11,provinces = "浙江",cityId = 8,city = "衢州市"},
		{id = 11,provinces = "浙江",cityId = 9,city = "舟山市"},
		{id = 11,provinces = "浙江",cityId = 10,city = "台州市"},
		{id = 11,provinces = "浙江",cityId = 11,city = "丽水市"},

	},
	[12] = {
		{id = 12,provinces = "安徽",cityId = 1,city = "合肥市"},
		{id = 12,provinces = "安徽",cityId = 2,city = "芜湖市"},
		{id = 12,provinces = "安徽",cityId = 3,city = "蚌埠市"},
		{id = 12,provinces = "安徽",cityId = 4,city = "淮南市"},
		{id = 12,provinces = "安徽",cityId = 5,city = "马鞍山市"},
		{id = 12,provinces = "安徽",cityId = 6,city = "淮北市"},
		{id = 12,provinces = "安徽",cityId = 7,city = "铜陵市"},
		{id = 12,provinces = "安徽",cityId = 8,city = "安庆市"},
		{id = 12,provinces = "安徽",cityId = 9,city = "黄山市"},
		{id = 12,provinces = "安徽",cityId = 10,city = "阜阳市"},
		{id = 12,provinces = "安徽",cityId = 11,city = "宿州市"},
		{id = 12,provinces = "安徽",cityId = 12,city = "滁州市"},
		{id = 12,provinces = "安徽",cityId = 13,city = "六安市"},
		{id = 12,provinces = "安徽",cityId = 14,city = "宣城市"},
		{id = 12,provinces = "安徽",cityId = 15,city = "池州市"},
		{id = 12,provinces = "安徽",cityId = 16,city = "亳州市"},

	},
	[13] = {
		{id = 13,provinces = "福建",cityId = 1,city = "福州市"},
		{id = 13,provinces = "福建",cityId = 2,city = "厦门市"},
		{id = 13,provinces = "福建",cityId = 3,city = "泉州市"},
		{id = 13,provinces = "福建",cityId = 4,city = "莆田市"},
		{id = 13,provinces = "福建",cityId = 5,city = "三明市"},
		{id = 13,provinces = "福建",cityId = 6,city = "漳州市"},
		{id = 13,provinces = "福建",cityId = 7,city = "南平市"},
		{id = 13,provinces = "福建",cityId = 8,city = "龙岩市"},
		{id = 13,provinces = "福建",cityId = 9,city = "宁德市"},

	},
	[14] = {
		{id = 14,provinces = "江西",cityId = 1,city = "南昌市"},
		{id = 14,provinces = "江西",cityId = 2,city = "景德镇市"},
		{id = 14,provinces = "江西",cityId = 3,city = "九江市"},
		{id = 14,provinces = "江西",cityId = 4,city = "萍乡市"},
		{id = 14,provinces = "江西",cityId = 5,city = "新余市"},
		{id = 14,provinces = "江西",cityId = 6,city = "鹰潭市"},
		{id = 14,provinces = "江西",cityId = 7,city = "赣州市"},
		{id = 14,provinces = "江西",cityId = 8,city = "宜春市"},
		{id = 14,provinces = "江西",cityId = 9,city = "上饶市"},
		{id = 14,provinces = "江西",cityId = 10,city = "吉安市"},
		{id = 14,provinces = "江西",cityId = 11,city = "抚州市"},

	},
	[15] = {
		{id = 15,provinces = "山东",cityId = 1,city = "济南市"},
		{id = 15,provinces = "山东",cityId = 2,city = "青岛市"},
		{id = 15,provinces = "山东",cityId = 3,city = "淄博市"},
		{id = 15,provinces = "山东",cityId = 4,city = "枣庄市"},
		{id = 15,provinces = "山东",cityId = 5,city = "东营市"},
		{id = 15,provinces = "山东",cityId = 6,city = "烟台市"},
		{id = 15,provinces = "山东",cityId = 7,city = "潍坊市"},
		{id = 15,provinces = "山东",cityId = 8,city = "泰安市"},
		{id = 15,provinces = "山东",cityId = 9,city = "威海市"},
		{id = 15,provinces = "山东",cityId = 10,city = "日照市"},
		{id = 15,provinces = "山东",cityId = 11,city = "滨州市"},
		{id = 15,provinces = "山东",cityId = 12,city = "德州市"},
		{id = 15,provinces = "山东",cityId = 13,city = "聊城市"},
		{id = 15,provinces = "山东",cityId = 14,city = "临沂市"},
		{id = 15,provinces = "山东",cityId = 15,city = "菏泽市"},
		{id = 15,provinces = "山东",cityId = 16,city = "莱芜市"},
		{id = 15,provinces = "山东",cityId = 17,city = "济宁市"},

	},
	[16] = {
		{id = 16,provinces = "河南",cityId = 1,city = "郑州市"},
		{id = 16,provinces = "河南",cityId = 2,city = "洛阳市"},
		{id = 16,provinces = "河南",cityId = 3,city = "商丘市"},
		{id = 16,provinces = "河南",cityId = 4,city = "安阳市"},
		{id = 16,provinces = "河南",cityId = 5,city = "新乡市"},
		{id = 16,provinces = "河南",cityId = 6,city = "许昌市"},
		{id = 16,provinces = "河南",cityId = 7,city = "平顶山市"},
		{id = 16,provinces = "河南",cityId = 8,city = "信阳市"},
		{id = 16,provinces = "河南",cityId = 9,city = "南阳市"},
		{id = 16,provinces = "河南",cityId = 10,city = "开封市"},
		{id = 16,provinces = "河南",cityId = 11,city = "焦作市"},
		{id = 16,provinces = "河南",cityId = 12,city = "鹤壁市"},
		{id = 16,provinces = "河南",cityId = 13,city = "濮阳市"},
		{id = 16,provinces = "河南",cityId = 14,city = "周口市"},
		{id = 16,provinces = "河南",cityId = 15,city = "漯河市"},
		{id = 16,provinces = "河南",cityId = 16,city = "驻马店市"},
		{id = 16,provinces = "河南",cityId = 17,city = "三门峡市"},
		{id = 16,provinces = "河南",cityId = 18,city = "济源市"},

	},
	[17] = {
		{id = 17,provinces = "湖北",cityId = 1,city = "武汉市"},
		{id = 17,provinces = "湖北",cityId = 2,city = "黄石市"},
		{id = 17,provinces = "湖北",cityId = 3,city = "十堰市"},
		{id = 17,provinces = "湖北",cityId = 4,city = "宜昌市"},
		{id = 17,provinces = "湖北",cityId = 5,city = "襄阳市"},
		{id = 17,provinces = "湖北",cityId = 6,city = "荆州市"},
		{id = 17,provinces = "湖北",cityId = 7,city = "荆门市"},
		{id = 17,provinces = "湖北",cityId = 8,city = "鄂州市"},
		{id = 17,provinces = "湖北",cityId = 9,city = "孝感市"},
		{id = 17,provinces = "湖北",cityId = 10,city = "黄冈市"},
		{id = 17,provinces = "湖北",cityId = 11,city = "咸宁市"},
		{id = 17,provinces = "湖北",cityId = 12,city = "随州市"},
		{id = 17,provinces = "湖北",cityId = 13,city = "恩施土家族苗族自治州"},
		{id = 17,provinces = "湖北",cityId = 14,city = "天门市"},
		{id = 17,provinces = "湖北",cityId = 15,city = "仙桃市"},
		{id = 17,provinces = "湖北",cityId = 16,city = "潜江市"},
		{id = 17,provinces = "湖北",cityId = 17,city = "神农架地区"},

	},
	[18] = {
		{id = 18,provinces = "湖南",cityId = 1,city = "长沙市"},
		{id = 18,provinces = "湖南",cityId = 2,city = "株洲市"},
		{id = 18,provinces = "湖南",cityId = 3,city = "湘潭市"},
		{id = 18,provinces = "湖南",cityId = 4,city = "衡阳市"},
		{id = 18,provinces = "湖南",cityId = 5,city = "邵阳市"},
		{id = 18,provinces = "湖南",cityId = 6,city = "岳阳市"},
		{id = 18,provinces = "湖南",cityId = 7,city = "张家界市"},
		{id = 18,provinces = "湖南",cityId = 8,city = "益阳市"},
		{id = 18,provinces = "湖南",cityId = 9,city = "常德市"},
		{id = 18,provinces = "湖南",cityId = 10,city = "娄底市"},
		{id = 18,provinces = "湖南",cityId = 11,city = "郴州市"},
		{id = 18,provinces = "湖南",cityId = 12,city = "永州市"},
		{id = 18,provinces = "湖南",cityId = 13,city = "怀化市"},
		{id = 18,provinces = "湖南",cityId = 14,city = "湘西土家族苗族自治州"},

	},
	[19] = {
		{id = 19,provinces = "广东",cityId = 1,city = "广州市"},
		{id = 19,provinces = "广东",cityId = 2,city = "深圳市"},
		{id = 19,provinces = "广东",cityId = 3,city = "珠海市"},
		{id = 19,provinces = "广东",cityId = 4,city = "汕头市"},
		{id = 19,provinces = "广东",cityId = 5,city = "韶关市"},
		{id = 19,provinces = "广东",cityId = 6,city = "佛山市"},
		{id = 19,provinces = "广东",cityId = 7,city = "江门市"},
		{id = 19,provinces = "广东",cityId = 8,city = "湛江市"},
		{id = 19,provinces = "广东",cityId = 9,city = "茂名市"},
		{id = 19,provinces = "广东",cityId = 10,city = "肇庆市"},
		{id = 19,provinces = "广东",cityId = 11,city = "惠州市"},
		{id = 19,provinces = "广东",cityId = 12,city = "梅州市"},
		{id = 19,provinces = "广东",cityId = 13,city = "汕尾市"},
		{id = 19,provinces = "广东",cityId = 14,city = "河源市"},
		{id = 19,provinces = "广东",cityId = 15,city = "阳江市"},
		{id = 19,provinces = "广东",cityId = 16,city = "清远市"},
		{id = 19,provinces = "广东",cityId = 17,city = "东莞市"},
		{id = 19,provinces = "广东",cityId = 18,city = "中山市"},
		{id = 19,provinces = "广东",cityId = 19,city = "潮州市"},
		{id = 19,provinces = "广东",cityId = 20,city = "揭阳市"},
		{id = 19,provinces = "广东",cityId = 21,city = "云浮市"},

	},
	[20] = {
		{id = 20,provinces = "广西",cityId = 1,city = "南宁市"},
		{id = 20,provinces = "广西",cityId = 2,city = "柳州市"},
		{id = 20,provinces = "广西",cityId = 3,city = "桂林市"},
		{id = 20,provinces = "广西",cityId = 4,city = "梧州市"},
		{id = 20,provinces = "广西",cityId = 5,city = "北海市"},
		{id = 20,provinces = "广西",cityId = 6,city = "防城港市"},
		{id = 20,provinces = "广西",cityId = 7,city = "钦州市"},
		{id = 20,provinces = "广西",cityId = 8,city = "贵港市"},
		{id = 20,provinces = "广西",cityId = 9,city = "玉林市"},
		{id = 20,provinces = "广西",cityId = 10,city = "百色市"},
		{id = 20,provinces = "广西",cityId = 11,city = "贺州市"},
		{id = 20,provinces = "广西",cityId = 12,city = "河池市"},
		{id = 20,provinces = "广西",cityId = 13,city = "来宾市"},
		{id = 20,provinces = "广西",cityId = 14,city = "崇左市"},

	},
	[21] = {
		{id = 21,provinces = "海南",cityId = 1,city = "海口市"},
		{id = 21,provinces = "海南",cityId = 2,city = "三亚市"},
		{id = 21,provinces = "海南",cityId = 3,city = "三沙市"},
		{id = 21,provinces = "海南",cityId = 4,city = "儋州市"},
		{id = 21,provinces = "海南",cityId = 5,city = "五指山市"},
		{id = 21,provinces = "海南",cityId = 6,city = "文昌市"},
		{id = 21,provinces = "海南",cityId = 7,city = "琼海市"},
		{id = 21,provinces = "海南",cityId = 8,city = "万宁市"},
		{id = 21,provinces = "海南",cityId = 9,city = "东方市"},
		{id = 21,provinces = "海南",cityId = 10,city = "定安县"},
		{id = 21,provinces = "海南",cityId = 11,city = "屯昌县"},
		{id = 21,provinces = "海南",cityId = 12,city = "澄迈县"},
		{id = 21,provinces = "海南",cityId = 13,city = "临高县"},
		{id = 21,provinces = "海南",cityId = 14,city = "琼中黎族苗族自治县"},
		{id = 21,provinces = "海南",cityId = 15,city = "保亭黎族苗族自治县"},
		{id = 21,provinces = "海南",cityId = 16,city = "白沙黎族自治县"},
		{id = 21,provinces = "海南",cityId = 17,city = "昌江黎族自治县"},
		{id = 21,provinces = "海南",cityId = 18,city = "乐东黎族自治县"},
		{id = 21,provinces = "海南",cityId = 19,city = "陵水黎族自治县"},

	},
	[22] = {
		{id = 22,provinces = "重庆",cityId = 1,city = "渝中区"},
		{id = 22,provinces = "重庆",cityId = 2,city = "大渡口区"},
		{id = 22,provinces = "重庆",cityId = 3,city = "江北区"},
		{id = 22,provinces = "重庆",cityId = 4,city = "沙坪坝区"},
		{id = 22,provinces = "重庆",cityId = 5,city = "九龙坡区"},
		{id = 22,provinces = "重庆",cityId = 6,city = "南岸区"},
		{id = 22,provinces = "重庆",cityId = 7,city = "北碚区"},
		{id = 22,provinces = "重庆",cityId = 8,city = "渝北区"},
		{id = 22,provinces = "重庆",cityId = 9,city = "巴南区"},
		{id = 22,provinces = "重庆",cityId = 10,city = "万州区"},
		{id = 22,provinces = "重庆",cityId = 11,city = "涪陵区"},
		{id = 22,provinces = "重庆",cityId = 12,city = "黔江区"},
		{id = 22,provinces = "重庆",cityId = 13,city = "长寿区"},
		{id = 22,provinces = "重庆",cityId = 14,city = "江津区"},
		{id = 22,provinces = "重庆",cityId = 15,city = "合川区"},
		{id = 22,provinces = "重庆",cityId = 16,city = "永川区"},
		{id = 22,provinces = "重庆",cityId = 17,city = "南川区"},
		{id = 22,provinces = "重庆",cityId = 18,city = "綦江区"},
		{id = 22,provinces = "重庆",cityId = 19,city = "大足区"},
		{id = 22,provinces = "重庆",cityId = 20,city = "潼南县"},
		{id = 22,provinces = "重庆",cityId = 21,city = "铜梁县"},
		{id = 22,provinces = "重庆",cityId = 22,city = "荣昌县"},
		{id = 22,provinces = "重庆",cityId = 23,city = "璧山县"},
		{id = 22,provinces = "重庆",cityId = 24,city = "梁平县"},
		{id = 22,provinces = "重庆",cityId = 25,city = "城口县"},
		{id = 22,provinces = "重庆",cityId = 26,city = "丰都县"},
		{id = 22,provinces = "重庆",cityId = 27,city = "垫江县"},
		{id = 22,provinces = "重庆",cityId = 28,city = "武隆县"},
		{id = 22,provinces = "重庆",cityId = 29,city = "忠县"},
		{id = 22,provinces = "重庆",cityId = 30,city = "开县"},
		{id = 22,provinces = "重庆",cityId = 31,city = "云阳县"},
		{id = 22,provinces = "重庆",cityId = 32,city = "奉节县"},
		{id = 22,provinces = "重庆",cityId = 33,city = "巫山县"},
		{id = 22,provinces = "重庆",cityId = 34,city = "巫溪县"},
		{id = 22,provinces = "重庆",cityId = 35,city = "石柱土家族自治县"},
		{id = 22,provinces = "重庆",cityId = 36,city = "秀山土家族苗族自治县"},
		{id = 22,provinces = "重庆",cityId = 37,city = "酉阳土家族苗族自治县"},
		{id = 22,provinces = "重庆",cityId = 38,city = "彭水苗族土家族自治县"},

	},
	[23] = {
		{id = 23,provinces = "四川",cityId = 1,city = "成都市"},
		{id = 23,provinces = "四川",cityId = 2,city = "自贡市"},
		{id = 23,provinces = "四川",cityId = 3,city = "攀枝花市"},
		{id = 23,provinces = "四川",cityId = 4,city = "泸州市"},
		{id = 23,provinces = "四川",cityId = 5,city = "德阳市"},
		{id = 23,provinces = "四川",cityId = 6,city = "绵阳市"},
		{id = 23,provinces = "四川",cityId = 7,city = "广元市"},
		{id = 23,provinces = "四川",cityId = 8,city = "遂宁市"},
		{id = 23,provinces = "四川",cityId = 9,city = "内江市"},
		{id = 23,provinces = "四川",cityId = 10,city = "乐山市"},
		{id = 23,provinces = "四川",cityId = 11,city = "南充市"},
		{id = 23,provinces = "四川",cityId = 12,city = "眉山市"},
		{id = 23,provinces = "四川",cityId = 13,city = "宜宾市"},
		{id = 23,provinces = "四川",cityId = 14,city = "广安市"},
		{id = 23,provinces = "四川",cityId = 15,city = "达州市"},
		{id = 23,provinces = "四川",cityId = 16,city = "雅安市"},
		{id = 23,provinces = "四川",cityId = 17,city = "巴中市"},
		{id = 23,provinces = "四川",cityId = 18,city = "资阳市"},
		{id = 23,provinces = "四川",cityId = 19,city = "阿坝藏族羌族自治州"},
		{id = 23,provinces = "四川",cityId = 20,city = "甘孜藏族自治州"},
		{id = 23,provinces = "四川",cityId = 21,city = "凉山彝族自治州"},

	},
	[24] = {
		{id = 24,provinces = "贵州",cityId = 1,city = "贵阳市"},
		{id = 24,provinces = "贵州",cityId = 2,city = "六盘水市"},
		{id = 24,provinces = "贵州",cityId = 3,city = "遵义市"},
		{id = 24,provinces = "贵州",cityId = 4,city = "安顺市"},
		{id = 24,provinces = "贵州",cityId = 5,city = "铜仁市"},
		{id = 24,provinces = "贵州",cityId = 6,city = "毕节市"},
		{id = 24,provinces = "贵州",cityId = 7,city = "黔南布依族苗族自治州"},
		{id = 24,provinces = "贵州",cityId = 8,city = "黔西南布依族苗族自治州"},
		{id = 24,provinces = "贵州",cityId = 9,city = "黔东南苗族侗族自治州"},

	},
	[25] = {
		{id = 25,provinces = "云南",cityId = 1,city = "昆明市"},
		{id = 25,provinces = "云南",cityId = 2,city = "曲靖市"},
		{id = 25,provinces = "云南",cityId = 3,city = "玉溪市"},
		{id = 25,provinces = "云南",cityId = 4,city = "保山市"},
		{id = 25,provinces = "云南",cityId = 5,city = "昭通市"},
		{id = 25,provinces = "云南",cityId = 6,city = "丽江市"},
		{id = 25,provinces = "云南",cityId = 7,city = "普洱市"},
		{id = 25,provinces = "云南",cityId = 8,city = "临沧市"},
		{id = 25,provinces = "云南",cityId = 9,city = "楚雄彝族自治州"},
		{id = 25,provinces = "云南",cityId = 10,city = "大理白族自治州"},
		{id = 25,provinces = "云南",cityId = 11,city = "红河哈尼族彝族自治州"},
		{id = 25,provinces = "云南",cityId = 12,city = "文山壮族苗族自治州"},
		{id = 25,provinces = "云南",cityId = 13,city = "西双版纳傣族自治州"},
		{id = 25,provinces = "云南",cityId = 14,city = "德宏傣族景颇族自治州"},
		{id = 25,provinces = "云南",cityId = 15,city = "怒江傈僳族自治州"},
		{id = 25,provinces = "云南",cityId = 16,city = "迪庆藏族自治州"},

	},
	[26] = {
		{id = 26,provinces = "西藏",cityId = 1,city = "拉萨市"},
		{id = 26,provinces = "西藏",cityId = 2,city = "昌都地区"},
		{id = 26,provinces = "西藏",cityId = 3,city = "林芝地区"},
		{id = 26,provinces = "西藏",cityId = 4,city = "山南地区"},
		{id = 26,provinces = "西藏",cityId = 5,city = "日喀则地区"},
		{id = 26,provinces = "西藏",cityId = 6,city = "那曲地区"},
		{id = 26,provinces = "西藏",cityId = 7,city = "阿里地区"},

	},
	[27] = {
		{id = 27,provinces = "陕西",cityId = 1,city = "西安市"},
		{id = 27,provinces = "陕西",cityId = 2,city = "宝鸡市"},
		{id = 27,provinces = "陕西",cityId = 3,city = "咸阳市"},
		{id = 27,provinces = "陕西",cityId = 4,city = "渭南市"},
		{id = 27,provinces = "陕西",cityId = 5,city = "铜川市"},
		{id = 27,provinces = "陕西",cityId = 6,city = "延安市"},
		{id = 27,provinces = "陕西",cityId = 7,city = "榆林市"},
		{id = 27,provinces = "陕西",cityId = 8,city = "汉中市"},
		{id = 27,provinces = "陕西",cityId = 9,city = "安康市"},
		{id = 27,provinces = "陕西",cityId = 10,city = "商洛市"},

	},
	[28] = {
		{id = 28,provinces = "甘肃",cityId = 1,city = "兰州市"},
		{id = 28,provinces = "甘肃",cityId = 2,city = "嘉峪关市"},
		{id = 28,provinces = "甘肃",cityId = 3,city = "金昌市"},
		{id = 28,provinces = "甘肃",cityId = 4,city = "白银市"},
		{id = 28,provinces = "甘肃",cityId = 5,city = "天水市"},
		{id = 28,provinces = "甘肃",cityId = 6,city = "武威市"},
		{id = 28,provinces = "甘肃",cityId = 7,city = "张掖市"},
		{id = 28,provinces = "甘肃",cityId = 8,city = "酒泉市"},
		{id = 28,provinces = "甘肃",cityId = 9,city = "平凉市"},
		{id = 28,provinces = "甘肃",cityId = 10,city = "庆阳市"},
		{id = 28,provinces = "甘肃",cityId = 11,city = "定西市"},
		{id = 28,provinces = "甘肃",cityId = 12,city = "陇南市"},
		{id = 28,provinces = "甘肃",cityId = 13,city = "临夏回族自治州"},
		{id = 28,provinces = "甘肃",cityId = 14,city = "甘南藏族自治州"},

	},
	[29] = {
		{id = 29,provinces = "青海",cityId = 1,city = "西宁市"},
		{id = 29,provinces = "青海",cityId = 2,city = "海东地区"},
		{id = 29,provinces = "青海",cityId = 3,city = "海北藏族自治州"},
		{id = 29,provinces = "青海",cityId = 4,city = "黄南藏族自治州"},
		{id = 29,provinces = "青海",cityId = 5,city = "海南藏族自治州"},
		{id = 29,provinces = "青海",cityId = 6,city = "果洛藏族自治州"},
		{id = 29,provinces = "青海",cityId = 7,city = "玉树藏族自治州"},
		{id = 29,provinces = "青海",cityId = 8,city = "海西蒙古族藏族自治州"},

	},
	[30] = {
		{id = 30,provinces = "宁夏",cityId = 1,city = "银川市"},
		{id = 30,provinces = "宁夏",cityId = 2,city = "石嘴山市"},
		{id = 30,provinces = "宁夏",cityId = 3,city = "吴忠市"},
		{id = 30,provinces = "宁夏",cityId = 4,city = "固原市"},
		{id = 30,provinces = "宁夏",cityId = 5,city = "中卫市"},

	},
	[31] = {
		{id = 31,provinces = "新疆",cityId = 1,city = "乌鲁木齐市"},
		{id = 31,provinces = "新疆",cityId = 2,city = "克拉玛依市"},
		{id = 31,provinces = "新疆",cityId = 3,city = "吐鲁番地区"},
		{id = 31,provinces = "新疆",cityId = 4,city = "哈密地区"},
		{id = 31,provinces = "新疆",cityId = 5,city = "昌吉回族自治州"},
		{id = 31,provinces = "新疆",cityId = 6,city = "博尔塔拉蒙古自治州"},
		{id = 31,provinces = "新疆",cityId = 7,city = "巴音郭楞蒙古自治州"},
		{id = 31,provinces = "新疆",cityId = 8,city = "阿克苏地区"},
		{id = 31,provinces = "新疆",cityId = 9,city = "克孜勒苏柯尔克孜自治州"},
		{id = 31,provinces = "新疆",cityId = 10,city = "喀什地区"},
		{id = 31,provinces = "新疆",cityId = 11,city = "和田地区"},
		{id = 31,provinces = "新疆",cityId = 12,city = "伊犁哈萨克自治州"},
		{id = 31,provinces = "新疆",cityId = 13,city = "塔城地区"},
		{id = 31,provinces = "新疆",cityId = 14,city = "阿勒泰地区"},
		{id = 31,provinces = "新疆",cityId = 15,city = "石河子市"},
		{id = 31,provinces = "新疆",cityId = 16,city = "阿拉尔市"},
		{id = 31,provinces = "新疆",cityId = 17,city = "图木舒克市"},
		{id = 31,provinces = "新疆",cityId = 18,city = "五家渠市"},
		{id = 31,provinces = "新疆",cityId = 19,city = "北屯市"},

	},
	[32] = {
		{id = 32,provinces = "香港",cityId = 1,city = "中西区"},
		{id = 32,provinces = "香港",cityId = 2,city = "湾仔区"},
		{id = 32,provinces = "香港",cityId = 3,city = "东区"},
		{id = 32,provinces = "香港",cityId = 4,city = "南区"},
		{id = 32,provinces = "香港",cityId = 5,city = "九龙城区"},
		{id = 32,provinces = "香港",cityId = 6,city = "油尖旺区"},
		{id = 32,provinces = "香港",cityId = 7,city = "观塘区"},
		{id = 32,provinces = "香港",cityId = 8,city = "黄大仙区"},
		{id = 32,provinces = "香港",cityId = 9,city = "深水埗区"},
		{id = 32,provinces = "香港",cityId = 10,city = "北区"},
		{id = 32,provinces = "香港",cityId = 11,city = "大埔区"},
		{id = 32,provinces = "香港",cityId = 12,city = "沙田区"},
		{id = 32,provinces = "香港",cityId = 13,city = "西贡区"},
		{id = 32,provinces = "香港",cityId = 14,city = "元朗区"},
		{id = 32,provinces = "香港",cityId = 15,city = "屯门区"},
		{id = 32,provinces = "香港",cityId = 16,city = "荃湾区"},
		{id = 32,provinces = "香港",cityId = 17,city = "葵青区"},
		{id = 32,provinces = "香港",cityId = 18,city = "离岛区"},

	},
	[33] = {
		{id = 33,provinces = "澳门",cityId = 1,city = "花地玛堂区"},
		{id = 33,provinces = "澳门",cityId = 2,city = "圣安多尼堂区"},
		{id = 33,provinces = "澳门",cityId = 3,city = "大堂区"},
		{id = 33,provinces = "澳门",cityId = 4,city = "望德堂区"},
		{id = 33,provinces = "澳门",cityId = 5,city = "风顺堂区"},
		{id = 33,provinces = "澳门",cityId = 6,city = "嘉模堂区"},
		{id = 33,provinces = "澳门",cityId = 7,city = "圣方济各堂区"},

	},
	[34] = {
		{id = 34,provinces = "台湾",cityId = 1,city = "台北市"},
		{id = 34,provinces = "台湾",cityId = 2,city = "新北市"},
		{id = 34,provinces = "台湾",cityId = 3,city = "台中市"},
		{id = 34,provinces = "台湾",cityId = 4,city = "台南市"},
		{id = 34,provinces = "台湾",cityId = 5,city = "高雄市"},
		{id = 34,provinces = "台湾",cityId = 6,city = "基隆市"},
		{id = 34,provinces = "台湾",cityId = 7,city = "新竹市"},
		{id = 34,provinces = "台湾",cityId = 8,city = "嘉义市"},
		{id = 34,provinces = "台湾",cityId = 9,city = "桃园县"},
		{id = 34,provinces = "台湾",cityId = 10,city = "新竹县"},
		{id = 34,provinces = "台湾",cityId = 11,city = "苗栗县"},
		{id = 34,provinces = "台湾",cityId = 12,city = "彰化县"},
		{id = 34,provinces = "台湾",cityId = 13,city = "南投县"},
		{id = 34,provinces = "台湾",cityId = 14,city = "云林县"},
		{id = 34,provinces = "台湾",cityId = 15,city = "嘉义县"},
		{id = 34,provinces = "台湾",cityId = 16,city = "屏东县"},
		{id = 34,provinces = "台湾",cityId = 17,city = "宜兰县"},
		{id = 34,provinces = "台湾",cityId = 18,city = "花莲县"},
		{id = 34,provinces = "台湾",cityId = 19,city = "台东县"},
		{id = 34,provinces = "台湾",cityId = 20,city = "澎湖县"},

	},
}