--This file is auto transformed from excel sheet file by script. 
--You **should NOT** edit it manually.
--Copyright @Guangyv Games 2016.

return {
 {   rankType = 1,   name = "关卡排行榜",   showNum = 100,   group = 1,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "关卡进度",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 1, 
 }, 
 {   rankType = 2,   name = "第五之塔榜",   showNum = 100,   group = 2,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "通关层数",   attrName3 = "",   attrShow = "第%s层",   showHero = 0,   showInMain = 1, 
 }, 
 {   rankType = 3,   name = "世界树之心榜",   showNum = 100,   group = 3,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "通关层数",   attrName3 = "",   attrShow = "第%s层",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 4,   name = "幻想之柱榜",   showNum = 100,   group = 4,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "通关层数",   attrName3 = "",   attrShow = "第%s层",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 5,   name = "虚拟之殿榜",   showNum = 100,   group = 5,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "通关层数",   attrName3 = "",   attrShow = "第%s层",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 6,   name = "竞技场榜",   showNum = 100,   group = 6,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "积分",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 1, 
 }, 
 {   rankType = 7,   name = "神族战力榜",   showNum = 100,   group = 7,   groupTab = "神  族",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "探员战力",   attrShow = "%s",   showHero = 1,   showInMain = 1, 
 }, 
 {   rankType = 8,   name = "魔族战力榜",   showNum = 100,   group = 7,   groupTab = "魔  族",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "探员战力",   attrShow = "%s",   showHero = 1,   showInMain = 1, 
 }, 
 {   rankType = 9,   name = "兽族战力榜",   showNum = 100,   group = 7,   groupTab = "兽  族",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "探员战力",   attrShow = "%s",   showHero = 1,   showInMain = 1, 
 }, 
 {   rankType = 10,   name = "人族战力榜",   showNum = 100,   group = 7,   groupTab = "人  族",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "探员战力",   attrShow = "%s",   showHero = 1,   showInMain = 1, 
 }, 
 {   rankType = 11,   name = "械族战力榜",   showNum = 100,   group = 7,   groupTab = "械  族",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "探员战力",   attrShow = "%s",   showHero = 1,   showInMain = 1, 
 }, 
 {   rankType = 12,   name = "日常首领排行",   showNum = 100,   group = 12,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "伤害",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 13,   name = "限时首领排行",   showNum = 100,   group = 13,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "伤害",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 14,   name = "图鉴头衔",   showNum = 100,   group = 14,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "点数",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 15,   name = "名人积分榜",   showNum = 100,   group = 15,   groupTab = "竞技场",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "玩家积分",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 18,   name = "个人总战力排行榜",   showNum = 100,   group = 36,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "玩家战力",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 1, 
 }, 
 {   rankType = 19,   name = "双重之圣榜",   showNum = 100,   group = 16,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "层数",   attrName3 = "",   attrShow = "第%s层",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 20,   name = "天境赛",   showNum = 100,   group = 26,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "战力",   attrName3 = "积分",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 101,   name = "0-30极地",   showNum = 100,   group = 101,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 102,   name = "31-50极地",   showNum = 100,   group = 102,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 103,   name = "51-60极地",   showNum = 100,   group = 103,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 104,   name = "61-70极地",   showNum = 100,   group = 104,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 105,   name = "71-80极地",   showNum = 100,   group = 105,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 106,   name = "81-90极地",   showNum = 100,   group = 106,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 107,   name = "91-100极地",   showNum = 100,   group = 107,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 108,   name = "101-110极地",   showNum = 100,   group = 108,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 109,   name = "111-130极地",   showNum = 100,   group = 109,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 110,   name = "131-150极地",   showNum = 100,   group = 110,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 111,   name = "151-170极地",   showNum = 100,   group = 111,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 112,   name = "171-190极地",   showNum = 100,   group = 112,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 113,   name = "终章极地",   showNum = 100,   group = 113,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "最高成绩",   attrName3 = "",   attrShow = "第%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 21,   name = "综合试炼",   showNum = 100,   group = 21,   groupTab = "综合试炼",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "最高纪录",   attrShow = "%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 22,   name = "人族试炼",   showNum = 100,   group = 21,   groupTab = "人族试炼",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "最高纪录",   attrShow = "%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 23,   name = "兽族试炼",   showNum = 100,   group = 21,   groupTab = "兽族试炼",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "最高纪录",   attrShow = "%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 24,   name = "械族试炼",   showNum = 100,   group = 21,   groupTab = "械族试炼",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "最高纪录",   attrShow = "%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 25,   name = "神魔试炼",   showNum = 100,   group = 21,   groupTab = "神魔试炼",   attrName1 = "探员信息",   attrName2 = "所属玩家",   attrName3 = "最高纪录",   attrShow = "%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 26,   name = "星辰圣所",   showNum = 100,   group = 114,   groupTab = "",   attrName1 = "玩家",   attrName2 = "最高层数",   attrName3 = "",   attrShow = "%s层",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 27,   name = "进度排行",   showNum = 100,   group = 115,   groupTab = "进度排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s层",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 28,   name = "金币排行",   showNum = 100,   group = 115,   groupTab = "金币排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 29,   name = "灵气排行",   showNum = 100,   group = 115,   groupTab = "灵气排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 30,   name = "进阶排行",   showNum = 100,   group = 115,   groupTab = "进阶排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 31,   name = "答题排行",   showNum = 100,   group = 115,   groupTab = "答题排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 32,   name = "次元裂缝",   showNum = 100,   group = 32,   groupTab = "",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 33,   name = "单人排行",   showNum = 100,   group = 33,   groupTab = "单人排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "队伍阵容",   attrShow = "第%s关第%s波",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 34,   name = "群体排行",   showNum = 100,   group = 33,   groupTab = "群体排行",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "队伍阵容",   attrShow = "第%s关第%s波",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 35,   name = "圣器通关榜",   showNum = 50,   group = 35,   groupTab = "",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最高记录",   attrShow = "%s关",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 36,   name = "魔灵收容所",   showNum = 100,   group = 36,   groupTab = "",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "总伤害",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 38,   name = "名人积分榜",   showNum = 100,   group = 15,   groupTab = "天境赛",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "玩家积分",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 39,   name = "探员试炼最速击杀3",   showNum = 3,   group = 200,   groupTab = "探员试炼",   attrName1 = "玩家排名",   attrName2 = "玩家信息",   attrName3 = "最快通关",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 40,   name = "点石成金榜",   showNum = 200,   group = 40,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "点金次数",   attrName3 = "",   attrShow = "%s次",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 41,   name = "委托寻宝榜",   showNum = 200,   group = 41,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "委托次数",   attrName3 = "",   attrShow = "%s次",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 43,   name = "行动达人榜",   showNum = 200,   group = 43,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "行动次数",   attrName3 = "",   attrShow = "%s次",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 44,   name = "得分排行",   showNum = 100,   group = 44,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "得分",   attrName3 = "",   attrShow = "%s次",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 45,   name = "赛区排行",   showNum = 100,   group = 45,   groupTab = "赛区排行",   attrName1 = "公会名",   attrName2 = "得分",   attrName3 = "",   attrShow = "%s次",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 46,   name = "全服排行",   showNum = 100,   group = 45,   groupTab = "全服排行",   attrName1 = "公会名",   attrName2 = "得分",   attrName3 = "",   attrShow = "%s次",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 47,   name = "跨服竞技场榜",   showNum = 100,   group = 47,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "积分",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 49,   name = "血荆之渊单BOSS积分榜",   showNum = 100,   group = 49,   groupTab = "单人排行",   attrName1 = "玩家信息",   attrName2 = "累计伤害与积分",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 50,   name = "血荆之渊总排行",   showNum = 100,   group = 50,   groupTab = "总排行",   attrName1 = "玩家信息",   attrName2 = "累计伤害",   attrName3 = "累计积分",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 53,   name = "积分总排行",   showNum = 100,   group = 52,   groupTab = "总排行",   attrName1 = "玩家信息",   attrName2 = "累计积分",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 55,   name = "人气票选排行",   showNum = 100,   group = 51,   groupTab = "总排行",   attrName1 = "探员",   attrName2 = "票数",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }, 
 {   rankType = 56,   name = "战神英雄榜",   showNum = 20,   group = 56,   groupTab = "",   attrName1 = "玩家信息",   attrName2 = "累计破点",   attrName3 = "",   attrShow = "%s",   showHero = 0,   showInMain = 0, 
 }
}