--This file is auto transformed from excel sheet file by script. 
--You **should NOT** edit it manually.
--Copyright @Guangyv Games 2016.

-- HeroLottery.xls
-- WorldSummon
-- DynamicConfigData.t_WorldSummon

return {
	[1] = {
		{HeroId = 35001,name = "白泽",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 35002,name = "腾蛇",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 35003,name = "罗素",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55005,name = "猫又",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 35007,name = "烬",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 35008,name = "虎男",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 35009,name = "贝蒂",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 34002,name = "蝶衣",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 35005,name = "米菈",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45001,name = "太白",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 15001,name = "后羿",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45002,name = "蔡文姬",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45003,name = "聂颖",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45004,name = "小乔",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45006,name = "妮娅",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45007,name = "荆轲",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45008,name = "女学生",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45009,name = "亚瑟",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45010,name = "仪狄",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45011,name = "占卜师",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55001,name = "干将",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55002,name = "斑衣",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55004,name = "狄福思",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55006,name = "匣中",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55007,name = "血小板",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 55008,name = "青龙",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 45005,name = "roca",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},
		{HeroId = 54001,name = "赢",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 1},

	},
	[2] = {
		{HeroId = 15002,name = "灵娲",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 15003,name = "嫦娥",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 15004,name = "米迦勒",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 15005,name = "板娘",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 15008,name = "芙蕾雅",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 15006,name = "加百列",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25001,name = "妮月",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25002,name = "魔王",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25004,name = "摄魂者",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25005,name = "妹喜",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25003,name = "莎莉丝特",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25006,name = "尼德霍格",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 25007,name = "猫面花",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 2},
		{HeroId = 35001,name = "白泽",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35002,name = "腾蛇",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35003,name = "罗素",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55005,name = "猫又",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35007,name = "烬",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35008,name = "虎男",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35010,name = "貔貅",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35009,name = "贝蒂",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 34002,name = "蝶衣",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 35005,name = "米菈",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45001,name = "太白",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 15001,name = "后羿",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45002,name = "蔡文姬",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45003,name = "聂颖",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45004,name = "小乔",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45006,name = "妮娅",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45007,name = "荆轲",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45008,name = "女学生",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45009,name = "亚瑟",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45010,name = "仪狄",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45011,name = "占卜师",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55001,name = "干将",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55002,name = "斑衣",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55004,name = "狄福思",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55006,name = "匣中",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55007,name = "血小板",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 55008,name = "青龙",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 45005,name = "roca",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},
		{HeroId = 54001,name = "赢",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 2},

	},
	[3] = {
		{HeroId = 25008,name = "红夫人",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 55009,name = "诺亚",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55010,name = "神乐",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 15002,name = "灵娲",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 15003,name = "嫦娥",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 15004,name = "米迦勒",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 15005,name = "板娘",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 15008,name = "芙蕾雅",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 15006,name = "加百列",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25001,name = "妮月",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25002,name = "魔王",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25004,name = "摄魂者",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25005,name = "妹喜",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25003,name = "莎莉丝特",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25006,name = "尼德霍格",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 25007,name = "猫面花",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 3},
		{HeroId = 35001,name = "白泽",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35002,name = "腾蛇",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35003,name = "罗素",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55005,name = "猫又",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35007,name = "烬",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35008,name = "虎男",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35010,name = "貔貅",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35009,name = "贝蒂",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 34002,name = "蝶衣",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 35005,name = "米菈",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45001,name = "太白",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 15001,name = "后羿",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45002,name = "蔡文姬",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45003,name = "聂颖",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45004,name = "小乔",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45006,name = "妮娅",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45007,name = "荆轲",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45008,name = "女学生",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45009,name = "亚瑟",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45010,name = "仪狄",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45011,name = "占卜师",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55001,name = "干将",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55002,name = "斑衣",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55004,name = "狄福思",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55006,name = "匣中",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55007,name = "血小板",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 55008,name = "青龙",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 45005,name = "roca",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},
		{HeroId = 54001,name = "赢",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 3},

	},
	[4] = {
		{HeroId = 25008,name = "红夫人",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 55009,name = "诺亚",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55010,name = "神乐",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 15002,name = "灵娲",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 15003,name = "嫦娥",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 15004,name = "米迦勒",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 15005,name = "板娘",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 15008,name = "芙蕾雅",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 15006,name = "加百列",heroStar = 5,category = 1, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25001,name = "妮月",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25002,name = "魔王",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25004,name = "摄魂者",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25005,name = "妹喜",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25003,name = "莎莉丝特",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25006,name = "尼德霍格",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 25007,name = "猫面花",heroStar = 5,category = 2, probability = 0,upType = 2,moduleId = 4},
		{HeroId = 35001,name = "白泽",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 35002,name = "腾蛇",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 35003,name = "罗素",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55005,name = "猫又",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 35007,name = "烬",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 35008,name = "虎男",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 35010,name = "貔貅",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 35009,name = "贝蒂",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 34002,name = "蝶衣",heroStar = 5,category = 3, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45001,name = "太白",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 15001,name = "后羿",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45002,name = "蔡文姬",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45003,name = "聂颖",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45004,name = "小乔",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45006,name = "妮娅",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45007,name = "荆轲",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45008,name = "女学生",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45009,name = "亚瑟",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45010,name = "仪狄",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45011,name = "占卜师",heroStar = 5,category = 4, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55001,name = "干将",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55002,name = "斑衣",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55004,name = "狄福思",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55006,name = "匣中",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55007,name = "血小板",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 55008,name = "青龙",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 45005,name = "roca",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},
		{HeroId = 54001,name = "赢",heroStar = 5,category = 5, probability = 0,upType = 1,moduleId = 4},

	},
}