--Name : TacticalController.lua
--Author : generated by FairyGUI
--Date : 2020-4-15
--Desc : 

local TacticalController = class("TacticalController",Controller)

function TacticalController:init()
	
end

function TacticalController:Tactical_UpdateTactical(_,params)
	print(69, "Tactical_UpdateTactical")
	--printTable(1, params)
	ModelManager.TacticalModel.activeTactical = params.tactical
	ModelManager.TacticalModel.lastActiveTactical = params.tactical
	ModelManager.TacticalModel:updateTactical(params.tactical, params.level)
	RedManager.updateValue("V_TACTICAL_ACTIVE",true)
	RedManager.updateValue("V_TACTICAL_HAS_NEW",true)
		
	Dispatcher.dispatchEvent(EventType.tatical_change)
	Dispatcher.dispatchEvent(EventType.tatical_activeNew)
	ModelManager.TacticalModel:redCheck()
end

function TacticalController:pata_showNext(_,params)
	print(69, "TacticalController.pata_showNext")
	--printTable(1, params)
	if ModelManager.TacticalModel.activeTactical then
      ViewManager.open("TacticalActiveHintView")
    end
end




return TacticalController