--Name : ExampleView.lua
--Author : generated by FairyGUI
--Date : 2020-4-11
--Desc : 

local ExampleView,Super = class("ExampleView", View)

function ExampleView:ctor()
	--LuaLog("ExampleView ctor")
	self._packName = "Example"
	self._compName = "ExampleView"
	self._rootDepth = LayerDepth.Window
	
end

function ExampleView:_initEvent( )
	
	
end

function ExampleView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:Example.ExampleView
		vmRoot.btn3 = viewNode:getChildAutoType("$btn3")--Button
		vmRoot.btn1 = viewNode:getChildAutoType("$btn1")--Button
		vmRoot.btn2 = viewNode:getChildAutoType("$btn2")--Button
	--{vmFieldsEnd}:Example.ExampleView
	--Do not modify above code-------------
end

function ExampleView:_initUI( )
	self:_initVM()
	
	self.btn1:addClickListener(function ()
			ViewManager.open("ControllerView")
		end)
	
	self.btn2:addClickListener(function ()
			
			ViewManager.open("ControllerView",{viewData = data,page = "oneView"})
		end)
	
	self.btn3:addClickListener(function ()
			ViewManager.open("ControllerView",{viewData = data,page = "PlayerHeadView",regCtrl = 1})
		end)
end




return ExampleView