--Name : oneView.lua
--Author : generated by FairyGUI
--Date : 2020-4-11
--Desc : 

local oneView,Super = class("oneView", View)

function oneView:ctor()
	--LuaLog("oneView ctor")
	self._packName = "Example"
	self._compName = "oneView"
	--self._rootDepth = LayerDepth.Window
	
	self.num = 0
end

function oneView:_initEvent( )
	
end

function oneView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:Example.oneView
		vmRoot.titlefont1 = viewNode:getChildAutoType("$titlefont1")--text
	--{vmFieldsEnd}:Example.oneView
	--Do not modify above code-------------
end

function oneView:_initUI( )
	self:_initVM()

end

function oneView:_refresh( )
	self.num = self.num + 1
	self.titlefont1:setText("我是oneView，我被刷新了"..self.num.."次")
end


return oneView