 return {
	[1] = {
		typeName = "太古神器",
		content = {
			{
				code = 700201,
				name = "噬魂素灯",
				descText = "仙人用于收复妖魔的神灯，可侵噬妖魔魂魄，当素灯体逐渐化红，可作为释放魂体傀儡的异界神器。",
				icon="Icon/Item/40920001.png",
				effect = "",
				src = "Model/GodWeapon/700201",
				pos = ccp(0,-10),
				extrapos = ccp(0,-0),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.1,
				effectY = 0,
				unActiveImg = "10001",--没解锁是图片
			},
			{
				code = 700202,
				name = "鬼母莲屏",
				descText = "传说天神赐予九州帝皇用于收伏冥界妖魔的奇异宝物，莲屏绕转时会发出的轻轻呢喃之语，宛如母亲之音在召回游荡于人世的冤魂邪魔。",
				icon="Icon/Item/40920002.png",
				effect = "",
				src = "Model/GodWeapon/700202",
				pos = ccp(0,-10),
				extrapos = ccp(0,-0),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.1,
				effectY = 0,
				unActiveImg = "10002",--没解锁是图片
			},
			{
				code = 700203,
				name = "紫霜幻剑",
				descText = "紫霜色之千年古剑，其内蕴藏无穷之力，当三剑幻化为一体时，可释放出开天辟地之力，斩杀世间妖魔。",
				icon="Icon/Item/40920003.png",
				effect = "",
				src = "Model/GodWeapon/700203",
				pos = ccp(0,-20),
				extrapos = ccp(0,-20),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.34,
				effectY = 0,
				unActiveImg = "10003",--没解锁是图片
			},	
			{
				code = 700204,
				name = "桃源金葫",
				descText = "酒仙翁珍藏的紫金光泽葫芦，内藏琼浆玉液，品尝之人犹如自入桃源之景，享受其中，不能自拔。",
				icon="Icon/Item/409200016.png",
				effect = "",
				src = "Model/GodWeapon/700204",
				pos = ccp(0,-20),
				extrapos = ccp(0,-20),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1,
				effectY = 0,
				unActiveImg = "10004",--没解锁是图片
			}
		}
	},
	[2] = {
		typeName = "洪荒神器",
		content = {
			{
				code = 700205,
				name = "金龙玉琴",
				descText = "自古传说以金龙口吐琼液制作的琴弦，纤细却坚硬无比，能弹奏此琴之人可呼风唤雨，与金龙携手作战。",
				icon="Icon/Item/40920004.png",
				effect = "",
				src = "Model/GodWeapon/700205",
				pos = ccp(0,-0),
				extrapos = ccp(0,-20),  --extrapos = ccp(0,-145), 
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.2,
				effectY = 0,
				unActiveImg = "20001",--没解锁是图片
			},
			{
				code = 700206,
				name = "火羽翎扇",
				descText = "古称火羽扇，乃上古异宝之一。相传挥动此扇，即可呼唤火翎前来助战，所到之处烽火四起，据说能毁灭一切。",
				icon="Icon/Item/40920005.png",
				effect = "",
				src = "Model/GodWeapon/700206",
				pos = ccp(0,-0),
				extrapos = ccp(0,-10),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.2,
				effectY = 0,
				unActiveImg = "20002",--没解锁是图片
			},
			{
				code = 700207,
				name = "荒古神笔",
				descText = "天地混沌之初，盘古开天辟地，荒古神迹现已难寻；天帝为复原美好江山华图，赐予帝皇神笔重绘美景；画中美景如幻似真，让人流连忘返，失去自我。",
				icon="Icon/Item/40920006.png",
				effect = "",
				src = "Model/GodWeapon/700207",
				pos = ccp(0,-0),
				extrapos = ccp(0,-10),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.2,
				effectY = 0,
				unActiveImg = "20003",--没解锁是图片
			},
			{
				code = 700208,
				name = "神隐仙铃",
				descText = "幽幽铃声显神通，遗落凡间的仙界法宝，仙神隐藏在铃中，当凡人诚心祈祷摇响此铃时，仙神可满足凡人之梦。",
				icon="Icon/Item/40920007.png",
				effect = "",
				src = "Model/GodWeapon/700208",
				pos = ccp(0,-20),
				extrapos = ccp(0,-15),
				activepos = ccp(0,-0),
				rotation = 0,
				defaultAction="stand",
				scale=1.2,
				effectY = 0,
				unActiveImg = "20004",--没解锁是图片
			}
		}
	},
	[3] = {
			typeName = "鸿蒙神器",
			content = {
				{
					code = 700209,
					name = "冥玄咒幡",
					descText = "原为天界重宝，可呼唤天界各路神兵相助；后因意外下落凡间，无人知晓其下落。",
					icon="Icon/Item/40920008.png",
					effect = "",
					src = "Model/GodWeapon/700209",
				pos = ccp(0,-20),
				extrapos = ccp(0,-15),
				activepos = ccp(0,-0),
					rotation = 0,
					defaultAction="stand",
					scale=1.3,
					effectY = 0,
					unActiveImg = "30001",--没解锁是图片
				},
				{
					code = 700210,
					name = "异域灵灯",
					descText = "帝皇取自异域的无上宝物，曾镇压西域异兽躁动，灵灯照耀之处均撼动摇晃；宇宙煌煌，天地失色，异域灵宝之威展露无遗。",
					icon="Icon/Item/40920009.png",
					effect = "",
					src = "Model/GodWeapon/700210",
				pos = ccp(0,-180),
				extrapos = ccp(0,-130),
				activepos = ccp(0,-90),
					rotation = 0,
					defaultAction="stand",
					scale=2.2,
					effectY = 0,
					unActiveImg = "30002",--没解锁是图片
				},
				{
					code = 700211,
					name = "伏羲碧琴",
					descText = "传闻为伏羲发明的琴瑟，弹奏时响起如玉般清脆悦耳声音；其乐声使人感到宁静祥和，据说拥有能支配万物心灵的神秘力量。",
					icon="Icon/Item/40920010.png",
					effect = "",
					src = "Model/GodWeapon/700211",
				pos = ccp(0,-200),
				extrapos = ccp(0,-125),
				activepos = ccp(0,-80),
					activePosY = 80,
					rotation = 0,
					defaultAction="stand",
					scale=2.5,
					effectY = 0,
					unActiveImg = "30003",--没解锁是图片
				},
				{
					code = 700212,
					name = "降魔仙杵",
					descText = "昆仑天宫中的秘宝法器，多年前的仙魔大战中，宫主倒握降魔杵将万千妖魔镇压在锁妖塔之中。",
					icon="Icon/Item/40920011.png",
					effect = "",
					src = "Model/GodWeapon/700212",
				pos = ccp(0,-200),
				extrapos = ccp(0,-120),
				activepos = ccp(0,-80),
					rotation = 0,
					defaultAction="stand",
					scale=2.5,
					effectY = 0,
					unActiveImg = "30004",--没解锁是图片
				},
			}
	},
	[4] = {
			typeName = "混沌神器",
			content = {
				{
					code = 700213,
					name = "金蟠画卷",
					descText = "天帝赐予九州皇族的至宝画卷，画内景色栩栩如生，可将世间万物囚禁于画内，画内之人真真假假难以分辨。",
					icon="Icon/Item/40920012.png",
					effect = "",
					src = "Model/GodWeapon/700213",
				pos = ccp(0,-200),
				extrapos = ccp(0,-150),
				activepos = ccp(0,-80),
					rotation = 0,
					defaultAction="stand",
					scale=2.5,
					effectY = 0,
					unActiveImg = "40001",--没解锁是图片
				},
				{
					code = 700214,
					name = "人皇神印",
					descText = "九州帝皇族的守护神器，其上刻塑有五方金龙盘绕。自古相传拥有此印之人，必为帝皇。",
					icon="Icon/Item/40920013.png",
					effect = "",
					src = "Model/GodWeapon/700214",
				pos = ccp(0,-50),
				extrapos = ccp(0,-25),
				activepos = ccp(0,-0),
					rotation = 0,
					defaultAction="stand",
					scale=1.2,
					effectY = 0,
					unActiveImg = "40002",--没解锁是图片
				},
				{
					code = 700215,
					name = "涅槃幽扇",
					descText = "原为九州帝皇族藏品，仅作观赏装饰用途；直到有缘人手执扇风，天色忽而转暗，大海浪涛涌起，宛如神明涅槃重生。",
					icon="Icon/Item/40920014.png",
					effect = "",
					src = "Model/GodWeapon/700215",
				pos = ccp(0,-130),
				extrapos = ccp(0,-95),
				activepos = ccp(0,-50),
					rotation = 0,
					defaultAction="stand",
					scale=2,
					effectY = 0,
					unActiveImg = "40003",--没解锁是图片
				},
				{
					code = 700216,
					name = "长明隐灯",
					descText = "原为九州帝皇宫殿内的照明灯具，在某日将军酒醉之时，被灯光指引至未曾发现的隐殿，从此便消失踪影。从此长明隐灯便被纳至藏品中。",
					icon="Icon/Item/40920014.png",
					--name = "嗜血珠",
					--descText = "诡秘之器，来历不明，嗜食生灵精血，凶煞异常充满戾气，但是威力巨大，吞噬越多造成的破坏力越大，有毁天灭地之能",
					--icon="Icon/Item/40920015.png",
					effect = "",
					src = "Model/GodWeapon/700216",
				pos = ccp(0,-250),
				extrapos = ccp(0,-150),
				activepos = ccp(0,-80),
					rotation = 0,
					defaultAction="stand",
					scale=2,
					effectY = 0,
					unActiveImg = "40004",--没解锁是图片
				}
			}
	}
}