return {
	GObject				= 0,
	GButton				= 1,
	GComboBox			= 2,
	GComponent			= 3,
	GGraph				= 4,
	GGroup				= 5,
	GImage				= 6,
	GLabel				= 7,
	GList				= 8,
	GLoader				= 9,
	GMovieClip			= 10,
	GProgressBar		= 11,
	GRichTextField		= 12,
	GRoot				= 13,
	GScrollBar			= 14,
	GSlider				= 15,
	GTextField			= 16,
	GTextInput			= 17,
	GTree				= 18,
}