--Name : ServiceCommitController.lua
--Author : generated by FairyGUI
--Date : 2020-6-12
--Desc :

local ServiceCommitController = class("ServiceCommitController", Controller)

function ServiceCommitController:init()
end

return ServiceCommitController
