--Name : SettleView.lua
--Author : generated by FairyGUI
--Date : 2020-3-6
--Desc : 

local SettleView,Super = class("SettleView", View)

function SettleView:ctor()
	--LuaLog("SettleView ctor")
	self._packName = "Arena"
	self._compName = "SettleView"
	self._isFullScreen = true
	--self._rootDepth = LayerDepth.Window
	
end

function SettleView:_initEvent( )
	
end

function SettleView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:Arena.SettleView
		--{vmFieldsEnd}:Arena.SettleView
	--Do not modify above code-------------
end

function SettleView:_initUI( )
	self:_initVM()

end




return SettleView