--Name : HeroCheckView.lua
--Author : generated by FairyGUI
--Date : 2020-6-2
--Desc : 

local HeroCheckView,Super = class("HeroCheckView", View)

function HeroCheckView:ctor()
	--LuaLog("HeroCheckView ctor")
	self._packName = "Handbook"
	self._compName = "HeroCheckView"
	--self._rootDepth = LayerDepth.Window
	
end

function HeroCheckView:_initEvent( )
	
end

function HeroCheckView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:Handbook.HeroCheckView
		vmRoot.labelList = viewNode:getChildAutoType("$labelList")--list
		vmRoot.cardList = viewNode:getChildAutoType("$cardList")--list
	--{vmFieldsEnd}:Handbook.HeroCheckView
	--Do not modify above code-------------
end

function HeroCheckView:_initUI( )
	self:_initVM()

end




return HeroCheckView