--Date :2021-01-21
--Author : generated by FairyGUI
--Desc : 

local ElfFinalSecondController = class("ElfFinalSecond",Controller)

function ElfFinalSecondController:init()
	
end

-- #最终大赏2
-- .PActivity_ElfFinalSecond {
-- 	reward 			1:*integer  #抽奖次数进度奖励
-- 	drawTimes       2:integer #抽奖总次数
-- }

function ElfFinalSecondController:Activity_UpdateData(_, params)
	if params.type ~= GameDef.ActivityType.ElfFinalSecond then
		return 	
	end
	if params and params.elfFinalSecond then
		ElfFinalSecondModel:initData(params.elfFinalSecond)
	end
end

return ElfFinalSecondController