--Name : ActivationCodeView.lua
--Author : generated by FairyGUI
--Date : 2020-6-8
--Desc : 

local ActivationCodeView,Super = class("ActivationCodeView", View)

function ActivationCodeView:ctor()
	--LuaLog("ActivationCodeView ctor")
	self._packName = "LoginAward"
	self._compName = "ActivationCodeView"
	--self._rootDepth = LayerDepth.Window
	self.txt_input = false
end

function ActivationCodeView:_initEvent( )
	
end

function ActivationCodeView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:LoginAward.ActivationCodeView
		vmRoot.bg = viewNode:getChildAutoType("$bg")--loader
		vmRoot.btn_exchange = viewNode:getChildAutoType("$btn_exchange")--Button
		vmRoot.input = viewNode:getChildAutoType("$input")--text
	--{vmFieldsEnd}:LoginAward.ActivationCodeView
	--Do not modify above code-------------
end

function ActivationCodeView:_initUI( )
	self:_initVM()
	self.txt_input = BindManager.bindTextInput(self.input)
	self.bg:setURL(PathConfiger.getBg("bg_ActivationCode.png"))
	self.btn_exchange:addClickListener(function()
			local textCode = self.txt_input:getText()
			if textCode == "" then 
				RollTips.show(Desc.activationCode_tips)
				return 
			end
			
			
			local function onSuccess(data)
				printTable(33,data)
				RollTips.show(Desc.activationCode_success)
				local rew = json.decode(data.item)
				local params = {}
				params.reward = {}
				for i = 1, #rew do
					local dd = {}
					dd.type = 3
					dd.code = rew[i].itemCode
					dd.amount = rew[i].num
					table.insert(params.reward,dd)
				end
				params.type = GameDef.GamePlayType.ActivationCode
				ModelManager.PlayerModel:set_awardData(params)
				Dispatcher.dispatchEvent(EventType.show_gameReward)
			end
			
			local function onFailed(data)
				printTable(33,data)
				RollTips.show(data.reason)
				
			end
			self.txt_input:setText("")
			PHPUtil.handleActivationCode("get",textCode,onSuccess,onFailed)
		end,33)
end




return ActivationCodeView