--Name : TimeLimitGiftDupController.lua
--Author : generated by FairyGUI
--Date : 2020-7-10
--Desc : 

--可重复推送的显示礼包控制器
local TimeLimitGiftDupController = class("TimeLimitGiftDupController",Controller)
local hasGift = false
local giftID = false
local indexFirst=1
function TimeLimitGiftDupController:init()
end

function TimeLimitGiftDupController:Activity_UpdateData( _,params )
	if params.type == GameDef.ActivityType.SurpriseGiftDup then
		if params and params.surpriseGiftDup and params.surpriseGiftDup.giftMap then
            printTable(1,"限时活动数据",params.surpriseGiftDup.giftMap)
            self:handleOpen(params.surpriseGiftDup.giftMap)
            TimeLimitGiftDupModel:initData(params.surpriseGiftDup.giftMap)
            indexFirst=2
		end
	end
end

function TimeLimitGiftDupController:handleOpen(giftMap)
    printTable(152,"限时活动数据",TimeLimitGiftDupModel.giftList)
   if indexFirst==1 then
            hasGift = false
            giftID = false
   else
        local hasMap={}
        for k, v in pairs(TimeLimitGiftDupModel.giftList) do
            -- hasMap[v.id]=v
            hasMap[v.uid]=v
        end

        for key, value in pairs(giftMap) do
            if hasMap[key]==nil then
                hasGift = true
                -- giftID = value.id
                giftID = value.uid
            end
        end
   end
    if hasGift and self:isMainUIShow() then
        ViewManager.open("TimeLimitGiftDupView",{isAutoOpen = true,giftID = giftID})
        hasGift = false
        giftID = false
    end
end

--角色升级
-- function TimeLimitGiftDupController:player_levelUp()
--     self:handleOpen(PlayerModel.level,1)
-- end

--获得英雄的星数
-- function TimeLimitGiftDupController:event_getHighStarHero(name,maxStar,cardCode)
--     print(150,"获得英雄",maxStar,cardCode)
--     self:handleOpen(maxStar,2,cardCode)
-- end

--购买礼包成功
-- function TimeLimitGiftDupController:buyGift_Success(name,rechargeType,money)
--     print(999,"购买礼包成功",rechargeType,money)
--     if rechargeType  == GameDef.StatFuncType.SFT_BuyNewServerGift then
--         self:handleOpen(money,3)
--     end
-- end

--秘武等级提升
-- function TimeLimitGiftDupController:secretWeapons_UpLevel(name,scretLevel)
--     print(152,"秘武等级提升",scretLevel)
--     self:handleOpen(scretLevel,4)
-- end

--界面变化
function TimeLimitGiftDupController:view_change(name)
    if hasGift and self:isMainUIShow() then
        Scheduler.schedule(function()
            ViewManager.open("TimeLimitGiftDupView",{isAutoOpen = true,giftID = giftID})
            hasGift = false
            giftID = false
        end,0.1,1)
    end
end

-- function TimeLimitGiftDupController:handleOpen(value,type,cardCode)
--     if hasGift then
--         return
--     end

--     local datas = ModelManager.TimeLimitGiftDupModel:getData()
--     if type==2 then
--        local configInfo= DynamicConfigData.t_hero[cardCode]
--        if not  configInfo then
--            return
--        end
--         for k,v in pairs(datas) do
--             local config = DynamicConfigData.t_SurpriseGiftDupConfig[v.id]
--             if config.giftType == type and value == config.openTask[1].value and self:togertherCategory(config.category,config.hero,configInfo.category,cardCode)==true then
--                 hasGift = true
--                 giftID = v.id
--                 break
--             end
--         end
--     else
--         for k,v in pairs(datas) do
--             local config = DynamicConfigData.t_SurpriseGiftDupConfig[v.id]
--             if config.giftType == type and value == config.openTask[1].value then
--                 hasGift = true
--                 giftID = v.id
--                 break
--             end
--         end
--     end


--     if hasGift and self:isMainUIShow() then
--         ViewManager.open("TimeLimitGiftDupView",{isAutoOpen = true,giftID = giftID})
--         hasGift = false
--         giftID = false
--     end
-- end

-- function TimeLimitGiftDupController:togertherCategory(attr,hero,category,cardId)
--     local has =false
--     if #attr>0 then
--         for key, value in pairs(attr) do
--             if value==category then
--                 has=true
--             end
--         end
--     elseif #hero>0 then
--         for key, value in pairs(attr) do
--             if value==cardId then
--                 has=true
--             end
--         end
--     end
--     printTable(150,"233333333",has)
--     return has
-- end

function TimeLimitGiftDupController:isMainUIShow()
    local mainUILayer = ViewManager.getParentLayer(LayerDepth.MainUI)
    if not mainUILayer then
        return false
    end

    local mainUIChildren = mainUILayer:getChildren()
    if not mainUIChildren then
        return false
    end

    if #mainUIChildren < 1 then
        return false
    end

    local views = ViewManager.getOpeningViews()
    local hasOther = false
    for k,v in pairs(views) do
        if v.window._viewName ~= "MainUIView" and v.window._viewName ~= "BroadcastView" then
            hasOther = true
            break
        end
    end

    return mainUIChildren[1]:isVisible() and not hasOther
end

return TimeLimitGiftDupController