--Name : SpecialgiftBagHeroTrialView.lua
--Author : generated by FairyGUI
--Date : 2020-5-29
--Desc : 神社祈福特惠礼包
local SpecialgiftBagBaseView = require "Game.Modules.SpecialgiftBag.SpecialgiftBagBaseView"
local SpecialgiftBagHeroTrialView, Super = class("SpecialgiftBagHeroTrialView", SpecialgiftBagBaseView)
local ItemCell = require "Game.UI.Global.ItemCell"
function SpecialgiftBagHeroTrialView:ctor()
    --LuaLog("SpecialgiftBagHeroTrialView ctor")
    self._packName = "OperatingActivities"
    self._compName = "SpecialgiftBagView"
	self.activityType = GameDef.ActivityType.HeroTrialPreferGift
	self.statFuncType = GameDef.StatFuncType.SFT_HeroTrialPreferGift
end


return SpecialgiftBagHeroTrialView
