--Date :2020-12-30
--Author : generated by FairyGUI
--Desc : 

local CrossLaddersShopView,Super = class("CrossLaddersShopView", Window)

function CrossLaddersShopView:ctor()
	--LuaLog("CrossLaddersShopView ctor")
	self._packName = "CrossLadders"
	self._compName = "CrossLaddersShopView"
	self._rootDepth = LayerDepth.PopWindow
	
end

function CrossLaddersShopView:_initEvent( )
	
end

function CrossLaddersShopView:_initVM( )
	local viewNode = self.view
	---Do not modify following code--------
	--{autoFields}:CrossLadders.CrossLaddersShopView
	self.blackbg = viewNode:getChildAutoType('blackbg')--GLabel
	self.btn_buy = viewNode:getChildAutoType('btn_buy')--GButton
	self.btn_cancel = viewNode:getChildAutoType('btn_cancel')--GButton
	self.frame = viewNode:getChildAutoType('frame')--GLabel
	self.itemCell = viewNode:getChildAutoType('itemCell')--GButton
	self.txt_limitTimes = viewNode:getChildAutoType('txt_limitTimes')--GTextField
	--{autoFieldsEnd}:CrossLadders.CrossLaddersShopView
	--Do not modify above code-------------
end

function CrossLaddersShopView:_initListener( )
	local conf = DynamicConfigData.t_SkyLadder[1]
	local ticketLimit = conf.ticketLimit
	local costDiamond = conf.costDiamond
	
	self.btn_buy:addClickListener(function()
		if CrossLaddersModel.buyTimes == ticketLimit then
			RollTips.show(Desc.CrossLadders_str22)
			return
		end	
		CrossLaddersModel:reqSkyLadder_Buy(1)
		ViewManager.close("CrossLaddersShopView")
	end)
	self.btn_buy:getChildAutoType("cost"):setText(costDiamond)

	self.btn_cancel:addClickListener(function()
		ViewManager.close("CrossLaddersShopView")
	end)

	local code = DynamicConfigData.t_SkyLadder[1].ticketCode
	local itemCell = BindManager.bindItemCell(self.itemCell)
	itemCell:setData(code,1,CodeType.ITEM)

	self.txt_limitTimes:setText(string.format(Desc.CrossLadders_str21,CrossLaddersModel.buyTimes,ticketLimit))
end

function CrossLaddersShopView:_initUI( )
	self:_initVM()
	self:_initListener()
end




return CrossLaddersShopView