--Name : PveStarTempleManView.lua
--Author : generated by FairyGUI
--Date : 2020-7-31
--Desc : 

local PveStarTempleManView,Super = class("PveStarTempleManView", Window)

function PveStarTempleManView:ctor()
	--LuaLog("PveStarTempleManView ctor")
	self._packName = "PveStarTemple"
	self._compName = "PveStarTempleManView"
	self._rootDepth = LayerDepth.PopWindow
	self.areaID = self._args.areaID
	self.pos = self._args.pos
	self.eventID = self._args.eventID
	self.configData = ModelManager.PveStarTempleModel:getEventConfig(5,0,self.eventID)
	self.optionList = {}
	self.optionDataList = {}
	self.resultDataList = {}
end

function PveStarTempleManView:_initEvent( )
	
end

function PveStarTempleManView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:PveStarTemple.PveStarTempleManView
		--{vmFieldsEnd}:PveStarTemple.PveStarTempleManView
	--Do not modify above code-------------
end

function PveStarTempleManView:_initUI( )
	self:_initVM()
	self.txtDesc = self.view:getChildAutoType("txtDesc")
	self.optionList[1] = self.view:getChildAutoType("op1")
	self.optionList[2] = self.view:getChildAutoType("op2")

	self.itemCell = BindManager.bindItemCell(self.view:getChildAutoType("itemCell"))

	self.view:getChildAutoType("n17"):setURL(PathConfiger.getPveStarTempleBG("man_frame"))

	self:updateView()
	self:updateItem()
	self:updateOptionList()
end

function PveStarTempleManView:_exit()
	self.areaID = false
	self.pos = false
	self.eventID = false
	self.optionDataList = false
	self.resultDataList = false
	self.configData = false
	self.optionList = false
end

function PveStarTempleManView:updateView()
	self.txtDesc:setText(self.configData.dec)
	--self._frame:setTitle(self.configData.title)
end

function PveStarTempleManView:updateItem()
	local item = DynamicConfigData.t_reward[self.configData.optionReward].item1[1]
	self.itemCell:setData(item.code,item.amount,item.type)
	self.itemCell:setIsShowName(true)
end

function PveStarTempleManView:updateOptionList()
	self.optionDataList = {}
	self.resultDataList = {}

	for word in string.gmatch(self.configData.option,'%[([^%[%]]+)%]') do
		table.insert(self.optionDataList,word)
	end

	for word in string.gmatch(self.configData.result,'%[([^%[%]]+)%]') do
		table.insert(self.resultDataList,word)
	end

	for i,v in ipairs(self.optionList) do
		v:setTitle(self.optionDataList[i])
		v:addClickListener(function()
			self:onOptionClick(i)
		end,1)
	end
end


function PveStarTempleManView:onOptionClick(index)
	RollTips.show(self.resultDataList[index])
	Dispatcher.dispatchEvent(EventType.PveStarTemple_EevntUse,{areaID = self.areaID,pos = self.pos})
	self:closeView()
end


return PveStarTempleManView