--Date :2020-12-26
--Author : generated by FairyGUI
--Desc :

local ExtraordinaryRewardsView, Super = class("ExtraordinaryRewardsView", Window)

function ExtraordinaryRewardsView:ctor()
    --LuaLog("ExtraordinaryRewardsView ctor")
    self._packName = "ExtraordinarylevelPvP"
    self._compName = "ExtraordinaryRewardsView"
    self._rootDepth = LayerDepth.PopWindow
    self.rewardGetArr = {}
end

function ExtraordinaryRewardsView:_initEvent()
end

function ExtraordinaryRewardsView:_initVM()
    local viewNode = self.view
    ---Do not modify following code--------
    --{autoFields}:ExtraordinarylevelPvP.ExtraordinaryRewardsView
	self.c1 = viewNode:getController('c1')--Controller
	self.frame = viewNode:getChildAutoType('frame')--GLabel
	self.list_reward1 = viewNode:getChildAutoType('list_reward1')--GList
	self.list_reward2 = viewNode:getChildAutoType('list_reward2')--GList
	self.list_type = viewNode:getChildAutoType('list_type')--GList
 --{autoFieldsEnd}:ExtraordinarylevelPvP.ExtraordinaryRewardsView
    --Do not modify above code-------------
end

function ExtraordinaryRewardsView:_initListener()
    self.list_type:setItemRenderer(
        function(index, obj)
            local title = obj:getChildAutoType("title")
            if index == 0 then
                obj:setSelected(true)
                self.c1:setSelectedIndex(0)
                self:showRewardList()
                title:setText("首达奖励")
            else
                title:setText("赛季奖励")
            end
            obj:removeClickListener(100)
            --池子里面原来的事件注销掉
            obj:addClickListener(
                function(context)
                    if index == 0 then
                        self:showRewardList()
                        self.c1:setSelectedIndex(0)
                    else
                        self.c1:setSelectedIndex(1)
                        self:showSaijiReward() 
                    end
                end,
                100
            )
        end
    )
    self.list_type:setNumItems(2)
end

function ExtraordinaryRewardsView:showSaijiReward() --赛季奖励
	local temp = {}
	local configReward = DynamicConfigData.t_LevelAward[2]
	for key, value in pairs(configReward) do
		temp[#temp + 1] = value
    end
     TableUtil.sortByMap(temp, {{key = "id", asc = false}})
    self.list_reward2:setItemRenderer(
		function(index, obj)
			local item = temp[index + 1]
            local img_duanwei = obj:getChildAutoType("img_duanwei")
            local txt_duanweidesc = obj:getChildAutoType("txt_duanweidesc")
            local duanweiname = ExtraordinarylevelPvPModel:getDanChinese(item.Level)
            txt_duanweidesc:setText(duanweiname)
            local duanweiURL = ExtraordinarylevelPvPModel:getDanIcon(item.Level)
            img_duanwei:setURL(duanweiURL)
			local list_prop = obj:getChild("list_prop")
            list_prop:setItemRenderer(
                function(idx2, obj2)
                    local itemcell = BindManager.bindItemCell(obj2)
                    local award = item.item[idx2 + 1]
                    itemcell:setData(award.code, award.amount, award.type)
                    -- itemcell:setIsHook(state == 3)
                end
            )
			list_prop:setNumItems(#item.item)
        end
	)
	self.list_reward2:setNumItems(#temp)
end

function ExtraordinaryRewardsView:showRewardList()
    self.rewardGetArr = ExtraordinarylevelPvPModel:getDuanweiRewardList()
    self.list_reward1:setItemRenderer(
        function(index, obj)
            local item = self.rewardGetArr[index + 1]
            local img_duanwei = obj:getChildAutoType("img_duanwei")
            local txt_duanweidesc = obj:getChildAutoType("txt_duanweidesc")
            local duanweiname = ExtraordinarylevelPvPModel:getDanChinese(item.Level)
            txt_duanweidesc:setText(duanweiname)
            local duanweiURL = ExtraordinarylevelPvPModel:getDanIcon(item.Level)
            img_duanwei:setURL(duanweiURL)
            local list_prop = obj:getChild("list_prop")
            list_prop:setItemRenderer(
                function(idx2, obj2)
                    local itemcell = BindManager.bindItemCell(obj2)
                    local award = item.item[idx2 + 1]
                    itemcell:setData(award.code, award.amount, award.type)
                    -- itemcell:setIsHook(state == 3)
                end
			)
			list_prop:setNumItems(#item.item)
            local ctrNum = self:getlingquState(item)
            local ctr = obj:getController("c1")
            ctr:setSelectedIndex(ctrNum)
            local btn_kelingqu = obj:getChildAutoType("btn_kelingqu")
            btn_kelingqu:removeClickListener(100)
            --池子里面原来的事件注销掉
            btn_kelingqu:addClickListener(
                function(context)
                    ExtraordinarylevelPvPModel:receiveDanReward(item.Level)
                end,
                100
            )
        end
    )
    self.list_reward1:setNumItems(#self.rewardGetArr)
end

function ExtraordinaryRewardsView:getlingquState(itemInfo)
    local lingqu = 0
    local mainInfo = ExtraordinarylevelPvPModel:getMainInfo()
    if not mainInfo then
        return lingqu
    end
    local dan = mainInfo.maxDan
    local danReward = ExtraordinarylevelPvPModel.danwaiRewardMap or {}
    local limitLv = itemInfo.Level
    if dan < limitLv then --未达成
        lingqu = 0
    elseif dan >= limitLv and not danReward[limitLv] then --可领取
        lingqu = 1
    elseif dan >= limitLv and danReward[limitLv] then --已领取
        lingqu = 2
    end
    return lingqu
end

function ExtraordinaryRewardsView:_initUI()
    self:setBg("bg_default.jpg")
    self:_initVM()
    self:_initListener()
end

function ExtraordinaryRewardsView:extraordinarylevelPvP_shoutongduanweijiangli()
    self.rewardGetArr = ExtraordinarylevelPvPModel:getDuanweiRewardList()
    if not self.rewardGetArr then
        return
    end
    self.list_reward1:setNumItems(#self.rewardGetArr)
end

return ExtraordinaryRewardsView
