--Name : UpGetAwardView.lua
--Author : generated by FairyGUI
--Date : 2020-9-3
--Desc : 精英招募阶段奖励 xhd

local UpGetAwardView,Super = class("UpGetAwardView", Window)

function UpGetAwardView:ctor()
	--LuaLog("UpGetAwardView ctor")
	self._packName = "UpGetCardActivity"
	self._compName = "UpGetAwardView"
	self._rootDepth = LayerDepth.PopWindow
	
end

function UpGetAwardView:_initEvent( )
	
end

function UpGetAwardView:_initVM( )
	local vmRoot = self
	local viewNode = self.view
	---Do not modify following code--------
	--{vmFields}:UpGetCardActivity.UpGetAwardView
		vmRoot.list = viewNode:getChildAutoType("$list")--list
	--{vmFieldsEnd}:UpGetCardActivity.UpGetAwardView
	--Do not modify above code-------------
end

function UpGetAwardView:_initUI( )
	self:_initVM()
	self.viewData = ActivityModel:getActityByType( GameDef.ActivityType.SpecialSummon )
	self.lotteryIdList = self.viewData.showContent.lotteryIdList
	printTable(1,self.lotteryIdList[1])
	self.config = UpGetCardActivityModel:getAllConfig( self.viewData.showContent.countReward)
	-- printTable(1,self.config)
	self.data = UpGetCardActivityModel:getData(  )
	-- printTable(1,self.data)
	self.list:setItemRenderer(function (index,obj)
		local curConfig = self.config[index+1]
		local curData = self.data.rewardRecordMap[index+1]
		local title = obj:getChildAutoType("n47")
		local progress = obj:getChildAutoType("progressBar")
		local itemCell = obj:getChildAutoType("itemCell")
		local btn_get =obj:getChildAutoType("btn_get")
		local statusCtrl = obj:getController("status")
		local img_red = btn_get:getChildAutoType("img_red")
		img_red:setVisible(false)
		title:setText(Desc.GetCard_Text16..curConfig.num..Desc.GetCard_Text17)
		progress:setMax(curConfig.num)
		if self.data.count>= curConfig.num then
			progress:setValue(curConfig.num)
			local flag = UpGetCardActivityModel:checkHadGetAward(curConfig.id)
			if flag then
				statusCtrl:setSelectedIndex(2)
			else
				statusCtrl:setSelectedIndex(1)
				img_red:setVisible(true)
				btn_get:removeClickListener(33)
				btn_get:addClickListener(function( ... )
					local params = {}
	 		    params.id = curConfig.id
	 		    params.activityId = self.viewData.id
		 		params.onSuccess = function (res )
		 		end
		 		RPCReq.Activity_SpecialSummon_GetReward(params, params.onSuccess)
				end,33)
			end
		else
			statusCtrl:setSelectedIndex(0)
			progress:setValue(self.data.count)
		end
		
		local itemcellObj = BindManager.bindItemCell(itemCell)
		itemcellObj:setIsBig(false)
		local itemData = ItemsUtil.createItemData({data = curConfig.reward[1]})
		itemcellObj:setItemData(itemData,CodeType.ITEM)
	end)
	self.list:setData(self.config)
end

function UpGetAwardView:update_upgetCard( ... )
	print(1,"领取成功刷新列表")
	self.list:setData(self.config)
end

return UpGetAwardView