--Name : SecretWeaponsMainView.lua
--Author : generated by FairyGUI
--Date : 2020-7-28
--Desc :

local SecretWeaponsMainView, Super = class("SecretWeaponsMainView", Window)

function SecretWeaponsMainView:ctor()
    --LuaLog("SecretWeaponsMainView ctor")
    self._packName = "SecretWeapons"
    self._compName = "SecretWeaponsMainView"
    self._rootDepth = LayerDepth.Window
    self.longTouchTag1 = false
    self.longTouchTag2 = false
    self.jingdutiaoAnima = false
    self.dengjitishengAnima = false
    self.selectedTabIndex = 0 --0秘武界面 1幻化界面
    self.showViewCtr = false
end

function SecretWeaponsMainView:_initVM()
    ---Do not modify following code--------
    --{vmFields}:SecretWeapons.SecretWeaponsMainView
    self.btn_promote = self.view:getChildAutoType("$btn_promote")
    self.bar_exp = self.view:getChildAutoType("$bar_exp")
    self.btn_assemble = self.view:getChildAutoType("$btn_assemble")
    self.btn_up1 = self.view:getChildAutoType("$btn_up1")
    self.btn_utupo = self.view:getChildAutoType("$btn_utupo")
    self.itemCelllist = self.view:getChildAutoType("$itemCelllist")
    self.btn_up2 = self.view:getChildAutoType("$btn_up2")
    self.btn_onekeyUp = self.view:getChildAutoType("$btn_onekeyUp")
    self.btn_reset = self.view:getChildAutoType("$btn_reset")
    self.list_specialAttr = self.view:getChildAutoType("$list_specialAttr")
    self.txt_lv = self.view:getChildAutoType("$txt_lv")
    self.list_generalAttr = self.view:getChildAutoType("$list_generalAttr")
    self.com_equip5 = self.view:getChildAutoType("$com_equip5")
    self.btn_attrOverview = self.view:getChildAutoType("$btn_attrOverview")
    self.btn_refine = self.view:getChildAutoType("$btn_refine")
    self.txt_skillLvDesc = self.view:getChildAutoType("txt_skillLvDesc")
    self.img_jingdutiaoani = self.view:getChildAutoType("img_jingdutiaoani")
    self.img_dengjitishengani = self.view:getChildAutoType("img_dengjitishengani")
    self.c1 = self.view:getController("c1")
    self.txt_tuponum = self.view:getChildAutoType("$txt_tuponum")
    self.showViewCtr = self.view:getController("showViewCtr")
    self.btn_weapon = self.view:getChildAutoType("btn_weapon")
    self.view:getChildAutoType("btn_weapon/img_red"):setVisible(false)
    self.btn_illusion = self.view:getChildAutoType("btn_illusion")
    --{vmFieldsEnd}:SecretWeapons.SecretWeaponsMainView
    --Do not modify above code-------------
end

--添加红点
function SecretWeaponsMainView:_addRed(...)
    --RedManager.register("V_SECRETWEAPONSUPLVRED1", self.btn_up1:getChildAutoType("img_red"),ModuleId.SecretWeapon.id)
    --RedManager.register("V_SECRETWEAPONSUPLVRED2",self.btn_up2:getChildAutoType("img_red"),ModuleId.SecretWeapon.id)
    RedManager.register(
        "V_SECRETWEAPONONEKEYUP",
        self.btn_onekeyUp:getChildAutoType("img_red"),
        ModuleId.SecretWeapon.id
    )
    RedManager.register("V_SECRETWEAPONSTUPORED", self.btn_utupo:getChildAutoType("img_red"), ModuleId.SecretWeapon.id)
    RedManager.register(
        "V_SECRETWEAPONSPROMOTERED",
        self.btn_promote:getChildAutoType("img_red"),
        ModuleId.SecretWeapon.id
    )
	
	RedManager.register("V_SECRETWEAPON_REFINE", self.btn_refine:getChildAutoType("img_red"), ModuleId.SecretWeapon.id)
    RedManager.register("V_SECRETWEAPON_ILLUSION", self.view:getChildAutoType("btn_illusion/img_red"))
end

function SecretWeaponsMainView:_initUI()
    self:_initVM()
    SecretWeaponsModel:godArmsGetInfo()
    self:setBg("SecretWeaponsMain.jpg")
    self.btn_onekeyUp:setTitle(Desc.SecretWeapones_str1)
    -- self:initBtnList()
    self.showViewCtr:setSelectedIndex(0)
    self:showSkillLvDesc()
    self:showBreakList()
     --突破属性
    self:showUpLvList()
    self:showCost()
end
function SecretWeaponsMainView:GodArms_ExpireTimeNotify()
   SecretWeaponsModel:godArmsGetInfo()
   self:setEquipPanel()
end

-- function SecretWeaponsMainView:initBtnList()
--     self.btn_list:setItemRenderer(function(idx,obj)
--         local index = idx + 1
--         local data  = BTN_LIST_NAME[index]
--         obj:getChildAutoType("btnName"):setText(data)
--         obj:removeClickListener(6)
--         obj:addClickListener(
--             function()
--                 if index == 1 then --秘武
--                     self.selectedTabIndex = 0
--                 else --幻化
--                     self.selectedTabIndex = 1
--                 end
--                 self:setEquipPanel()
--             end,6)
--         if index == 2 then 
--             local redDot = RedManager.getTips()
--             obj:getChildAutoType("img_red"):setVisible(redDot)
--         else
--             obj:getChildAutoType("img_red"):setVisible(false)
--         end
--     end)
--     self.btn_list:setData(BTN_LIST_NAME)
-- end

function SecretWeaponsMainView:setEquipPanel()
    self.showViewCtr:setSelectedIndex(self.selectedTabIndex)
    if self.selectedTabIndex == 0 then 
        self:showNormalEquip()
    elseif self.selectedTabIndex == 1 then 
        self:showIllusionEquip()
    end
end
function SecretWeaponsMainView:showSkillLvDesc()
    local isShow, curskillLv, str = SecretWeaponsModel:getskillLvDesc()
    local decs = string.format(Desc.SecretWeapones_SkillLvDesc, curskillLv)
    self.txt_skillLvDesc:setText(decs..str)
    self.txt_skillLvDesc:setVisible(isShow)
end

function SecretWeaponsMainView:showNormalEquip()
    self.showViewCtr:setSelectedIndex(0)
    local serverInfo = SecretWeaponsModel.secretWeaponsInfo
    if not serverInfo then
        return
    end
    local equipMap = serverInfo.godArmsMap
    if not equipMap then
        return
    end
    local configInfo = DynamicConfigData.t_godArmsTrigger
    for i = 1, 5, 1 do
        if tolua.isnull(self.view) then
            return
        end
        local configItem = configInfo[i]
        local item = self.view:getChildAutoType("$com_equip" .. i)
        local bar = self.view:getChildAutoType("$bar" .. i)
        local equImg = item:getChildAutoType("img_goods")
        local txt_name = item:getChildAutoType("txt_name")
        local txt_lv = item:getChildAutoType("txt_lv")
        local gCtr1 = item:getController("c1")
        local gCtr2 = item:getController("c2")
        gCtr2:setSelectedIndex(1)
        if not configItem then
            if bar then
                bar:setMax(100)
                bar:setValue(0)
            end
            gCtr1:setSelectedIndex(2)
            txt_name:setText(DescAuto[253]) -- [253]="敬请期待"
            item:removeClickListener(100)
            item:addClickListener(
                function(context)
                    RollTips.show(DescAuto[253]) -- [253]="敬请期待"
                end,
                100
            )
        else
            local equipurl = SecretWeaponsModel:getEquipById(configItem.id)
            equImg:setURL(equipurl)
            --	local imgred= item:getChildAutoType("img_red")
            local img_zhuangpei = item:getChildAutoType("img_zhuangpei")
            local iszhuangpei = self:isshowZhuangpeiIcon(configItem.id)
            -- local red= self:getEquipRed(configItem.id)
            -- imgred:setVisible(red)
            local equipInfo = equipMap[i]
            if bar then
                bar:setMax(100)
                if equipInfo then
                    bar:setValue(100)
                else
                    bar:setValue(0)
                end
            end
            if equipInfo then
                gCtr1:setSelectedIndex(0)
                equImg:setGrayed(false)
                txt_name:setText(configItem.name)
                txt_lv:setText(equipInfo.level)
                img_zhuangpei:setVisible(iszhuangpei)
                item:removeClickListener(100)
                --池子里面原来的事件注销掉
                item:addClickListener(
                    function(context)
                        ViewManager.open("SecretWeaponStrainView", {id = configItem.id})
                    end,
                    100
                )
            else
                img_zhuangpei:setVisible(iszhuangpei)
                local limitDesc = SecretWeaponsModel:getEquipOpenDesc(configItem.id)
                gCtr1:setSelectedIndex(1)
                equImg:setGrayed(true)
                txt_name:setText(limitDesc)
                txt_lv:setText("0")
                item:removeClickListener(100)
                item:addClickListener(
                    function(context)
                        RollTips.show(DescAuto[254]) -- [254]="请前往激活"
                    end,
                    100
                )
            end
        end
    end
end

function SecretWeaponsMainView:showIllusionEquip()
    self.showViewCtr:setSelectedIndex(self.selectedTabIndex)
    local serverInfo = SecretWeaponsModel.secretWeaponsInfo
    if not serverInfo then
        return
    end
    local equipMap = serverInfo.godArmsMap
    if not equipMap then
        return
    end
    local configInfo = DynamicConfigData.t_godArmsTrigger
    for i = 1, 5, 1 do
        if tolua.isnull(self.view) then
            return
        end
        local configItem = configInfo[1000+i]
        local item = self.view:getChildAutoType("$com_equipEx" .. i)
        local bar = self.view:getChildAutoType("$barEx" .. i)
        local equImg = item:getChildAutoType("img_goods")
        local txt_name = item:getChildAutoType("txt_name")
        local txt_lv = item:getChildAutoType("txt_lv")
        local img_red = item:getChildAutoType("img_red")
        local gCtr1 = item:getController("c1")
        local gCtr2 = item:getController("c2")
        gCtr2:setSelectedIndex(1)
        if not configItem then
            if bar then
                bar:setMax(100)
                bar:setValue(0)
            end
            gCtr1:setSelectedIndex(2)
            txt_name:setText(DescAuto[253]) -- [253]="敬请期待"
            item:removeClickListener(100)
            item:addClickListener(
                function(context)
                    RollTips.show(DescAuto[253]) -- [253]="敬请期待"
                end,
                100
            )
        else
            local maxId = self:getMaxEquipId()
            local equipurl = SecretWeaponsModel:getEquipById(configItem.id)
            equImg:setURL(equipurl)
            --  local imgred= item:getChildAutoType("img_red")
            local img_zhuangpei = item:getChildAutoType("img_zhuangpei")
            -- local red= self:getEquipRed(configItem.id)
            -- imgred:setVisible(red)
            local equipInfo = equipMap[1000+i]
            if bar then
                bar:setMax(100)
                if equipInfo and i < maxId then
                    bar:setValue(100)
                else
                    bar:setValue(0)
                end
            end
            if equipInfo then
                gCtr1:setSelectedIndex(0)
                txt_name:setText(configItem.name)
                txt_lv:setText(equipInfo.level)
                local iszhuangpei = self:isshowZhuangpeiIcon(configItem.id)
                img_zhuangpei:setVisible(iszhuangpei)
                equImg:setGrayed(false)
                item:removeClickListener(100)
                --池子里面原来的事件注销掉
                item:addClickListener(
                    function(context)
                        ViewManager.open("SecretWeaponStrainView", {id = configItem.id})
                    end,
                    100
                )
            else
                local iszhuangpei = self:isshowZhuangpeiIcon(configItem.id)
                img_zhuangpei:setVisible(iszhuangpei)
                local limitDesc = SecretWeaponsModel:getEquipOpenDesc(configItem.id)
                gCtr1:setSelectedIndex(1)
                txt_name:setText(limitDesc)
                txt_lv:setText("0")
                equImg:setGrayed(true)
                item:removeClickListener(100)
                item:addClickListener(
                    function(context)
                        local godArmsMissionInfo = DynamicConfigData.t_godArmsMission[configItem.id]
                        if godArmsMissionInfo then --需要完成任务获取奖励
                            local isAllGot = SecretWeaponsModel:getAllTaskGotInfo(configItem.id)
                            if not isAllGot then 
                                ViewManager.open("SecretWeaponTaskView",{id = configItem.id}) 
                            else
                                ViewManager.open("SecretWeaponActiveView",{id = configItem.id}) 
                            end
                        else --道具激活
                           ViewManager.open("SecretWeaponActiveView",{id = configItem.id}) 
                        end
                    end,
                    100
                )
            end
            local redDot = self:checkRedDot(configItem.id)
            img_red:setVisible(redDot)
        end
    end
end

function SecretWeaponsMainView:checkRedDot(id)
    local godArmsMissionInfo = DynamicConfigData.t_godArmsMission[id]
    local godArmsTriggerInfo = DynamicConfigData.t_godArmsTrigger[id]
    local taskInfo = SecretWeaponsModel.secretWeaponsTaskInfo
    local serverInfo = SecretWeaponsModel.secretWeaponsInfo
    local equipMap = serverInfo.godArmsMap
    if godArmsMissionInfo then --需要完成任务获取奖励
        local isAllGot = SecretWeaponsModel:getAllTaskGotInfo(id)
        if not isAllGot then 
            for _,v in pairs(taskInfo) do
                if not equipMap[id] and v.finish and not v.got then 
                    return true
                end
            end
        else
            if not equipMap[id] then --没有激活
                if godArmsTriggerInfo.condtion and godArmsTriggerInfo.condtion[1] == 3 then 
                    local itemCost = godArmsTriggerInfo.itemCost[1]
                    local haveNum = PackModel:getItemsFromAllPackByCode(itemCost.code)
                    if haveNum >= itemCost.amount then 
                        return true
                    end
                end
            end
        end
    else --道具激活
        if not equipMap[id] then --没有激活
            if godArmsTriggerInfo.condtion and godArmsTriggerInfo.condtion[1] == 3 then 
                local itemCost = godArmsTriggerInfo.itemCost[1]
                local haveNum = PackModel:getItemsFromAllPackByCode(itemCost.code)
                if haveNum >= itemCost.amount then 
                    return true
                end
            end
        end
    end
    return false
end

function SecretWeaponsMainView:SecretWeapons_active()
   self:setEquipPanel()
end

function SecretWeaponsMainView:SecretWeapons_reward()
   self:setEquipPanel()
end

function SecretWeaponsMainView:SecretWeaponsMainView_refresh()
   self:setEquipPanel()
end

function SecretWeaponsMainView:getMaxEquipId()
    local serverInfo = SecretWeaponsModel.secretWeaponsInfo
    if not serverInfo then
        return
    end
    local equipMap = serverInfo.godArmsMap
    if not equipMap then
        return
    end
    if next(equipMap) == nil then
        return
    end
    local maxId = 1
    for key, value in pairs(equipMap) do
        if value.id >= maxId then
            maxId = value.id
        end
    end
    return maxId
end

function SecretWeaponsMainView:showCost(...)
    local curLevel, nextLevel, curexp = SecretWeaponsModel:getEquipLvAndExp()
    local str = "Lv." .. ColorUtil.formatColorString1(curLevel, "#6aff60") .. "/" .. nextLevel
    if not tolua.isnull(self.txt_lv) then
        self.txt_lv:setText(str)
    end
    local bartext = self.bar_exp:getChildAutoType("title")
    local state = 0
    if SecretWeaponsModel:isMaxLevel() == true then --已满级
        self.c1:setSelectedIndex(2)
        bartext:setText(DescAuto[255]) -- [255]="已满级"
        self.bar_exp:setMax(100)
        self.bar_exp:setValue(100)
        state = 3
    else
        if curLevel < nextLevel then --可升级
            self.c1:setSelectedIndex(0)
            local nextExp = SecretWeaponsModel:getEquipBarExp()
            if SecretWeaponsModel.isShowJingdutiaoAnim == true then
                self.jingdutiaoAnima = SecretWeaponsModel:jingdutiaoAnim(self.img_jingdutiaoani)
                self.dengjitishengAnima = SecretWeaponsModel:dengjishengjiAnim(self.img_dengjitishengani)
                SecretWeaponsModel.isShowJingdutiaoAnim = false
            end
            self.bar_exp:setMax(nextExp)
            self.bar_exp:setValue(curexp)
            state = 1
        else
            if curLevel == nextLevel then
                if SecretWeaponsModel.isShowJingdutiaoAnim == true then
                    self.jingdutiaoAnima = SecretWeaponsModel:jingdutiaoAnim(self.img_jingdutiaoani)
                    self.dengjitishengAnima = SecretWeaponsModel:dengjishengjiAnim(self.img_dengjitishengani)
                    SecretWeaponsModel.isShowJingdutiaoAnim = false
                end
            end
            --可突破
            self.bar_exp:setMax(100)
            self.bar_exp:setValue(100)
            bartext:setText(DescAuto[256]) -- [256]="可突破"
            self.c1:setSelectedIndex(1)
            state = 2
        end
    end
    local cost = {}
    if state == 1 then
        -- local btnState1=GMethodUtil:getGoodsEnough(cost[1])
        -- local btnState2=GMethodUtil:getGoodsEnough(cost[2])
        -- local costConfig=DynamicConfigData.t_godArmsCost
        -- local param1=costConfig[1].param
        -- local param2=costConfig[2].param
        -- self.btn_up1:setTitle("经验+"..param1)
        -- self.btn_up2:setTitle("经验+"..param2)
        -- self.btn_up1:setTouchable(btnState1);
        -- self.btn_up2:setTouchable(btnState2);
        -- -- self.btn_up1:setGrayed(not btnState1)
        -- -- self.btn_up2:setGrayed(not btnState2)
        -- if btnState1==true then
        -- 	self.btn_up1:getController("c1"):setSelectedIndex(0);
        -- 	self.btn_up1:getController("button"):setSelectedIndex(0);
        -- else
        -- 	self.btn_up1:getController("c1"):setSelectedIndex(1);
        -- 	self.btn_up1:getController("button"):setSelectedIndex(1);
        -- end
        -- if btnState2==true then
        -- 	self.btn_up2:getController("c1"):setSelectedIndex(0);
        -- 	self.btn_up2:getController("button"):setSelectedIndex(0);
        -- else
        -- 	self.btn_up2:getController("c1"):setSelectedIndex(1);
        -- 	self.btn_up2:getController("button"):setSelectedIndex(1);
        -- end
        --printTable(152,"升级的属性》》》》》》》》》》？？",btnState1,btnState2)
        cost = SecretWeaponsModel:getupLevelcost(1)
    elseif state == 2 then
        cost = SecretWeaponsModel:getupLevelcost(2)
        local tupoState = GMethodUtil:getGoodsEnough(cost[1])
        self.btn_utupo:setTouchable(tupoState)
        self.btn_utupo:getController("button"):setSelectedIndex(tupoState and 0 or 2)
        local color = ColorUtil.textColor_Light.green
        if tupoState == false then
            color = ColorUtil.textColor_Light.red
        end
		self.txt_tuponum:setColor(color)
        local tupohasNum = ModelManager.PackModel:getItemsFromAllPackByCode(cost[1].code)
        local colorStr = cost[1].amount
        local tupoStr =
            string.format("%s/", MathUtil.toSectionStr(tupohasNum)) .. GMethodUtil.getSizeString(colorStr, 20) --消耗/总数量
        self.txt_tuponum:setText(tupoStr)
    end
    local configInfo = DynamicConfigData.t_godArmsCost
    self.itemCelllist:setItemRenderer(
        function(idx2, obj2)
            local itemcell = BindManager.bindItemCell(obj2)
            local award = cost[idx2 + 1]
            itemcell:setData(award.code, award.amount, award.type)
            local hasNum = ModelManager.PackModel:getItemsFromAllPackByCode(award.code)
            local color = "#FFFFFF"
            if hasNum == 0 then
                color = "#FF6464"
            end
            local str = ColorUtil.formatColorString1(MathUtil.toSectionStr(hasNum), color)
            itemcell:setAmountStr(str)
            itemcell:setExpNum(string.format(DescAuto[257], configInfo[idx2 + 1].param)) -- [257]="%s经验"
            if state == 1 then
                itemcell:setIsShowExp(true)
            else
                itemcell:setIsShowExp(false)
            end
        end
    )
    self.itemCelllist:setNumItems(#cost)
end

function SecretWeaponsMainView:showBreakList(...)
    local curStage = SecretWeaponsModel:getCurStage()
    local configInfo = DynamicConfigData.t_godArmsStage
    local attrMap = {}
    for key, value in pairs(configInfo) do
        if next(value.exAttr) ~= nil then
            table.insert(attrMap, value.godArmsStage)
        end
    end
    local function sortFunc(arg1, arg2)
        return arg1 < arg2
    end
    TableUtil.sort(attrMap, sortFunc)
    local pos = SecretWeaponsModel:getItemIndex(attrMap, curStage)
    if tolua.isnull(self.list_specialAttr) then
        return
    end
    self.list_specialAttr:setItemRenderer(
        function(idx2, obj2)
            local color = "#FFFFFF"
            if idx2 + 1 <= pos then
                color = "#6AFF60"
            end
            local confItem = DynamicConfigData.t_godArmsStage[attrMap[idx2+1]]
            --local attr=confItem.exAttr[1]
            local limitLevel = confItem.maxLevel
            local txt_desc1 = obj2:getChildAutoType("txt_desc1")
            txt_desc1:setText(ColorUtil.formatColorString1(confItem.StageDesc, color)) -- [250]="突破" -- [251]="级"
            -- local attrName= GMethodUtil:getFightAttrName(attr.type)
            -- local attrNum=GMethodUtil:getFightAttrName(attr.type,attr.value)
            local txt_desc2 = obj2:getChildAutoType("txt_desc2")
            --txt_desc2:setText(ColorUtil.formatColorString1(attrName.."+"..attrNum,color))
            txt_desc2:setText(ColorUtil.formatColorString1(confItem.desc, color))
        end
    )
    self.list_specialAttr:setNumItems(#attrMap)
    if pos - 1 <= 0 then
        pos = 1
    end
    self.list_specialAttr:scrollToView(pos - 1, true, true)
end

function SecretWeaponsMainView:showUpLvList(...)
    local isMax = SecretWeaponsModel:isMaxLevel()
    local curLevel = SecretWeaponsModel:getCurLevel()
    local curAttr = DynamicConfigData.t_godArmsLevel[curLevel].addAttr
    local nextLevel = curLevel + 1
    if isMax == true then
        nextLevel = curLevel
    end
    local nextAttr = DynamicConfigData.t_godArmsLevel[nextLevel].addAttr
    -- printTable(28,"swwwwwwwwwwwwwwwwwssswwwsada",curAttr,nextAttr)
    self.list_generalAttr:setItemRenderer(
        function(index, obj)
            local c1 = obj:getController("c1")
            if isMax == true then
                c1:setSelectedIndex(1)
            else
                c1:setSelectedIndex(0)
            end
            local attr = curAttr[index + 1]
            local nextattr = nextAttr[index + 1]
            local attrName = GMethodUtil:getFightAttrName(attr.type)
            local attrNum = GMethodUtil:getFightAttrName(attr.type, attr.value)
            local nextattrNum = GMethodUtil:getFightAttrName(nextattr.type, nextattr.value)
            local txt_attrName = obj:getChildAutoType("txt_attrName")
            txt_attrName:setText(attrName)
            local txt_cur = obj:getChildAutoType("txt_cur")
            txt_cur:setText(attrNum)
            local txt_next = obj:getChildAutoType("txt_next")
            txt_next:setText(nextattrNum)
        end
    )
    self.list_generalAttr:setNumItems(#curAttr)
end

-- function SecretWeaponsMainView:getEquipRed(id)
-- 	local Remine= SecretWeaponsModel:getRemineSkillPoint()--剩余技能点
-- 	local yijihuo =SecretWeaponsModel:getEquipOpen(id)--已激活
-- 	local lv= SecretWeaponsModel:getEquipSkillLv(id)
-- 	local ConfigSkill=DynamicConfigData.t_godArms
-- 	local configOd= ConfigSkill[id]
-- 	local max=#configOd
-- 	if not configOd[lv] then
-- 		return
-- 	end
-- 	local curCost=configOd[lv].point
-- 	if Remine>0 and Remine>=curCost and yijihuo==true and lv<max then
-- 		return true
-- 	end
-- 	return false
-- end

--事件初始化
function SecretWeaponsMainView:_initEvent(...)
    -- self.btn_up1:addClickListener(
    -- 	function(context)
    -- 	local cost=SecretWeaponsModel:getupLevelcost(1)
    -- 	local  btnState1 =PlayerModel:checkCostEnough(cost[1],true)
    -- 	printTable(31,"qqqqqqqqqqq",btnState1)
    -- 	if btnState1==true then
    -- 		SecretWeaponsModel:godArmsAddExp(1,1)
    -- 	else
    -- 		local itemInfo=ItemConfiger.getInfoByCode(cost[1].code, cost[1].type)
    -- 		local str= itemInfo.name.."物品不足"
    -- 		RollTips.show(str)
    -- 		end
    --     end
    -- )

    -- self.btn_up2:addClickListener(
    -- 	function(context)
    -- 		local cost=SecretWeaponsModel:getupLevelcost(1)
    -- 		local btnState2=PlayerModel:checkCostEnough(cost[2],true)--GMethodUtil:getGoodsEnough(cost[2])
    -- 		if btnState2==true then
    -- 			SecretWeaponsModel:godArmsAddExp(2,1)
    -- 		else
    -- 			self.btn_up2:getController("c1"):setSelectedIndex(1);
    -- 			self.btn_up2:getController("button"):setSelectedIndex(1);
    -- 			local itemInfo=ItemConfiger.getInfoByCode(cost[2].code, cost[2].type)
    -- 			local str= itemInfo.name.."物品不足"
    -- 			RollTips.show(str)
    -- 		end
    --     end
    -- )

    self.btn_onekeyUp:addClickListener(
        function(context)
            SecretWeaponsModel:godArmsOnekeyUpLevel()
        end
    )

    -- self.btn_up1:addLongPressListener(function (context)
    -- self.longTouchTag1=	Scheduler.schedule(function()
    -- 	local cost=SecretWeaponsModel:getupLevelcost(1)
    -- 	local btnState1 =PlayerModel:checkCostEnough({type=cost[1].type,code=cost[1].code,amount=1})
    -- 	if btnState1==true then
    -- 		SecretWeaponsModel:godArmsAddExp(1,10)
    -- 	end
    -- end,0.15,0)
    -- end, 1,function (context)
    -- 		Scheduler.unschedule(self.longTouchTag1)
    -- 	end)

    -- self.btn_up2:addLongPressListener(function (context)
    -- 	self.longTouchTag2=	Scheduler.schedule(function()
    -- 		local cost=SecretWeaponsModel:getupLevelcost(1)
    -- 		local btnState1 =PlayerModel:checkCostEnough({type=cost[2].type,code=cost[2].code,amount=1})
    -- 		if btnState1==true then
    -- 			SecretWeaponsModel:godArmsAddExp(2,1)
    -- 		else
    -- 			if not tolua.isnull(self.btn_up2) then
    -- 				self.btn_up2:getController("c1"):setSelectedIndex(1);
    -- 				self.btn_up2:getController("button"):setSelectedIndex(1);
    -- 			end
    -- 		end
    -- 		end,0.3,0)
    -- 			end, 1,function (context)
    -- 			Scheduler.unschedule(self.longTouchTag2)
    -- 	end)

    self.btn_utupo:addClickListener(
        function(context)
            local cost = SecretWeaponsModel:getupLevelcost(2)
            local tupoState = PlayerModel:checkCostEnough(cost[1])
             --GMethodUtil:getGoodsEnough(cost[1])
            if tupoState == true then
                SecretWeaponsModel:godArmsUpStage()
            else
                local itemInfo = ItemConfiger.getInfoByCode(cost[1].code, cost[1].type)
                local str = itemInfo.name .. DescAuto[258] -- [258]="物品不足"
                RollTips.show(str)
            end
        end
    )

    self.btn_assemble:addClickListener(
        --装配
        function(...)
            ViewManager.open("SecretWeaponDeployView")
        end
    )

    self.btn_promote:addClickListener(
        --提升
        function(...)
            ViewManager.open("SecretWeaponPromoteView")
        end
    )

    self.btn_attrOverview:addClickListener(
        --总览
        function(...)
            ViewManager.open("SecretWeaponAddattrView")
        end
    )

    self.btn_refine:addClickListener(
        --精炼
        function(...)
			local godArmsMap = ModelManager.SecretWeaponsModel.secretWeaponsInfo.godArmsMap
			if not godArmsMap or #godArmsMap == 0 then
				RollTips.show(Desc.SecretWeapones_acviveFirst)
				return
			end
            --ViewManager.open("SecretWeaponsRefinedView")
			ModuleUtil.openModule(ModuleId.SecretWeaponsRefined.id)
        end
    )

    self.btn_reset:addClickListener(
         --重置
        function(...)
            local info = {}
            info.text = DescAuto[259] -- [259]="是否重置所有技能点?"
            info.type = "yes_no"
            info.mask = true
            info.onYes = function()
                SecretWeaponsModel:godArmsResetSkill()
            end
            Alert.show(info)
        end
    )
    self.btn_weapon:addClickListener(
        function()
            self.selectedTabIndex = 0
            self:setEquipPanel()
        end
    )
     self.btn_illusion:addClickListener(
        function()
            local hasOpen = ModuleUtil.moduleOpen(268, true )
            if hasOpen then
                self.selectedTabIndex = 1
                self:setEquipPanel() 
            else
                self.showViewCtr:setSelectedIndex(0)
            end
        end
    )
end

function SecretWeaponsMainView:secretWeapons_chongzhijinengdian(...) --重置技能点
    self:setEquipPanel()
end

function SecretWeaponsMainView:secretWeapons_shengjijinengdian(...) --升级技能点
    self:setEquipPanel()
end

function SecretWeaponsMainView:secretWeapons_getInfo(...)
    self:setEquipPanel()
    self:showBreakList()
     --突破属性
    self:showUpLvList()
 --升级属性
end
--升级刷新
function SecretWeaponsMainView:secretWeapons_AddExp(...)
    self:setEquipPanel()
    self:showCost()
    self:showUpLvList()
 --升级属性
end
--突破刷新
function SecretWeaponsMainView:secretWeapons_UpStage(...)
    self:setEquipPanel()
    self:showCost()
    self:showBreakList()
 --突破属性
end

function SecretWeaponsMainView:pack_item_change(_, data)
    self:showCost()
end

function SecretWeaponsMainView:isshowZhuangpeiIcon(curId)
    local isShow = false
    if SecretWeaponsModel.secretWeaponsInfo.curId and SecretWeaponsModel.secretWeaponsInfo.curId == curId then
        isShow = true
    end
    return isShow
end

function SecretWeaponsMainView:secretWeapons_IndexIdChoose(...) --装配
    self:setEquipPanel()
end

--页面退出时执行
function SecretWeaponsMainView:_exit(...)
    if self.jingdutiaoAnima then
        SpineUtil.clearEffect(self.jingdutiaoAnima)
    end
    if self.dengjitishengAnima then
        SpineUtil.clearEffect(self.dengjitishengAnima)
	end
	SecretWeaponsModel.isShowJingdutiaoAnim = false
end

return SecretWeaponsMainView
