--货币逻辑比较简单主要在货币模块一次做好，这块日后要添加货币只需要添加类型即可用，要存库的对应的odm也要处理一下。
return {
    Gold                = 1,            --金币
    Diamond             = 2,            --钻石
    HeroScore           = 3,            --英雄积分
    Friend              = 4,		    --友情币
    GuildMoney          = 5, 		    --公会币
    GuildContri         = 6,            --公会贡献 
    EndlessRoad         = 7,			--极地币
    Maze                = 8,			--迷宫币
    DelegateCoin        = 9,			--委托币
    SpecialCoin         = 10,			--特异积分币
    PvpCoin             = 11,           --竞技币
    Detective           = 12,           --精英币
    WarOrder            = 13,           --战令经验
    HigherPvpCoin       = 14,           --高阶竞技场币
    Boundary            = 15,           --临界币
    GashaponCoin        = 16,           --扭蛋币
    GashaponScore       = 17,           --扭蛋积分
    CourageCoin         = 18,           --勇气徽章
    ElfWarOrderExp      = 19,           --精灵战令经验
    DreamPvpScore       = 20,           --梦主积分 -- 只有定义不能放入背包
    HeroTrialScore      = 21,           --试炼积分
    HorizonPvpScore     = 22,           --天域币
    GuildPackScore      = 23,           --公会宝库积分
    FashionPoint        = 24,           --时装点券
	CrossArenaCoin      = 25,           --跨服竞技场币
    PowerTurnTable      = 26,           --时空聚集积分
    BoundaryWarOrderExp = 27,           --临界战令经验
    GodsPrayCoin        = 28,           --神灵祈愿币
    WorldTeamAreanCoin  = 29,           --组队竞技币
    CrossSuperMundane   = 30,           --超凡积分
    SkyLadder           = 31,           --天梯积分
    MazeWarOrderExp     = 32,           --逆境迷宫战令经验
    EndlessRoadWarOrderExp = 33,        --极地探索战令经验
    GuildLeagueCoin     = 34,           --传奇币
    TopArenaCoin        = 35,           --巅峰币
    HallowWarOrderExp   = 36,           --圣器副本战令经验
    ColorDiamond        = 37,           --彩钻
    SkyLadChampion      = 38,           --天梯冠军赛积分
    GodMarketScore      = 39,           --神格积分
    LanternCoin         = 40,           --元宵币
    LanternScore        = 41,           --元宵积分
    NewHeroCoin         = 42,           --新英雄兑换币
    NewHeroDrawCoin     = 43,           --新英雄召唤抽奖券
    FiveWeekHeroCoin    = 44,           --第5周新英雄兑换币
}