return {
	Chapters = 1, 			--推图榜
	NormalTower = 2,		--普通塔榜
	OrcsTower = 3,			--兽族塔榜
	HumanTower = 4,			--人族塔榜
	MachineryTower = 5,		--机械塔榜
	Arena = 6,				--竞技场榜
	FairyCobmat = 7,		--仙族战力榜
	DemonCombat = 8,		--魔族战力榜
	OrcsCombat = 9,			--兽族战力榜
	HumanCombat = 10,		--人族战力榜
	MachineryCombat = 11,   --机械战力榜
	GuildDailyBoss = 12,	--公会日常BOSS榜
	GuildLimitBoss = 13,	--公会限时BOSS榜
	HeroTotemsTitle = 14,   --图鉴头衔
	WorldArenaPlayerScore = 15, --世界擂台赛 玩家历史积分榜
	HeroCodeCombat = 16,	--英雄code战力榜
	Level		   = 17,	--玩家等级榜
	MaxCombat 	  = 18, 	--玩家最大战力榜
	FairyDemonTower = 19,	--仙魔塔榜
	HigherPvp		= 20,	--高阶竞技场
	TopChallengeCommon		= 21,	--无尽试炼 综合试炼
	TopChallengeHuman		= 22,	--无尽试炼 人族试炼
	TopChallengeOrc			= 23,	--无尽试炼 兽族试炼
	TopChallengeMachine		= 24,	--无尽试炼 械族试炼
	TopChallengeFairy		= 25,	--无尽试炼 仙魔
	PveStarTemple 			= 26,	--晨星1V1
	FairyLandFloor          = 27,   --秘境层数排行
	FairyLandMoney          = 28,   --秘境金币排行
	FairyLandAura           = 29,   --秘境灵气排行
	FairyLandAdvanced       = 30,   --秘境进阶石排行
	FairyLandQuestion       = 31,   --秘境答题排行
	GuildWorldBoss			= 32,	--公会跨服BOSS
	DreamLandSingle			= 33, 	--幻境单人模式排行版
	DreamLandMultiple		= 34, 	--幻境全体模式排行版
	Hallow					= 35,	--圣器副本排行
	EvilMountainBoss		= 36,	--魔灵山boss排行榜
	NewHeroCopy				= 37,	--新英雄副本榜
	WorldSkyPvpPlayerScore  = 38,	--天境赛世界擂台赛 玩家历史积分榜
	HeroTrial				= 39,	--探员试炼排行
	GoldMagic				= 40,	--点石成金排行
	DelegateContend			= 41,	--委托夺宝排行 
	Boundary 				= 42,   --临界之旅
	QuickBattle				= 43,	--作战行动排行
	GuildPvpMatchPlayer		= 44,	--公会联赛 参赛玩家排名
	GuildPvpGroupGuild		= 45,	--公会联赛 本跨服分组 公会排名
	GuildPvpWorldGuild		= 46,	--公会联赛 全服公会排名
	CrossArenaScore			= 47,	--跨服竞技场积分排行榜
	GuildPvpGuildPlayerScore	= 48,	--公会联赛 本公会玩家赛季积分排名
	BloodAbyssSingle		= 49,	--幻墨之境单个boss积分
	BloodAbyssMultiple		= 50,	--幻墨之境总积分
	TopArenaScore			= 51,	--巅峰竞技积分排行榜
	SkyLadder				= 52,	--天梯赛排行榜
	WorkTogetherScore		= 53,	--协议大作战-积分排行榜
	SkyLadChampion			= 54,	--天梯赛冠军赛积分排行榜
	HeroVote				= 55,   --人气探员票选数排行榜
	PowerPlan				= 56,	--异能计划排行榜
	NewYear					= 57,	--新年活动排行榜
	-- 100 - 500
	EndlessRoadFirst 		= 101, --远征阶段排行
	EndlessRoadSecond 		= 102, --远征阶段排行
	EndlessRoadThird 		= 103, --远征阶段排行
	EndlessRoadFourth 		= 104, --远征阶段排行
	EndlessRoadFifth		= 105, --远征阶段排行
	EndlessRoadSixth 		= 106, --远征阶段排行
	EndlessRoadSevenTh 		= 107, --远征阶段排行
	EndlessRoadEighth 		= 108, --远征阶段排行
	EndlessRoadNinth 		= 109, --远征阶段排行
	EndlessRoadTenth 		= 110, --远征阶段排行
	EndlessRoadEleventh 	= 111, --远征阶段排行
	EndlessRoadTwelfth 		= 112, --远征阶段排行
	EndlessRoadThirteenth	= 113, --远征阶段排行
	--
	-- 500 - 1000 对应 等级战力排行
	LvlCombatFirst 		= 501, --等级战力阶段排行
	LvlCombatSecond 	= 502, --等级战力阶段排行
	LvlCombatThird 		= 503, --等级战力阶段排行
	LvlCombatFourth 	= 504, --等级战力阶段排行
	LvlCombatFifth		= 505, --等级战力阶段排行
	LvlCombatSixth 		= 506, --等级战力阶段排行
	LvlCombatSevenTh 	= 507, --等级战力阶段排行
	LvlCombatEighth 	= 508, --等级战力阶段排行
	LvlCombatNinth 		= 509, --等级战力阶段排行
	LvlCombatTenth 		= 510, --等级战力阶段排行
	LvlCombatEleventh 	= 511, --等级战力阶段排行
	LvlCombatTwelfth 	= 512, --等级战力阶段排行
	LvlCombatThirteenth	= 513, --等级战力阶段排行
	--跨服自定义排行榜  2000 ~ 3000 
	CorssHorizonPvp 	= 2000, --天域排行榜
	CrossSuperMundane   = 2001, --超凡排行榜
}