return {
	-- 玩家个人统计
	SFT_SaleGiftPack = 1,			-- 直购礼包
	SFT_Privilege = 2,				-- 购买特权
	SFT_BuyFund = 3,				-- 购买成长基金
	SFT_BuyWarOrder = 4,            -- 购买战令高阶执照
	SFT_CollectStar = 5,			-- 购买集星特权
	SFT_BuySuperFund = 6,			-- 购买超级基金
	SFT_WeekCard = 7,				-- 购买周卡
	SFT_SurpriseGift = 8,			-- 购买限时礼包
	SFT_DailyGift = 9,				-- 购买每日礼包
	SFT_BuyNewServerGift = 10,      -- 购买新服专享礼包
	SFT_BuyMoonGift = 11,	        -- 购买月度限购礼包
	SFT_WeekGift = 12,	        	-- 每周礼包
	SFT_Preferentialk = 13, 		-- 特惠礼包
	SFT_LimitGift = 14,				-- 限时礼包
	SFT_NewWeekCard = 15,			-- 黑金周卡
	SFT_EquipGift = 16,				-- 装备礼包
	SFT_OneKeyDailyGift = 17,		-- 一键购买每日礼包奖励 
	SFT_GashaponGift	= 18,		-- 扭蛋礼包
	SFT_ElfGift = 19,				-- 精灵商城礼包
	SFT_RuneShop= 20,				-- 符文商城礼包
	SFT_CustomLimitGift = 21,		-- 自选礼包
	SFT_ElfTourShop = 22,			-- 巡礼礼包
	SFT_SurpriseGiftDup = 23,		-- 推送礼包(可重复)
	SFT_GroupBuyGift	= 24,		-- 团购礼包
	SFT_SurpriseGiftEx	= 25,		-- 后台推送礼包
	SFT_ElfWarOrder		= 26,		-- 精灵战令购买
	SFT_ShrinePrayShop	= 27,		-- 祈福礼包购买
	SFT_HeroTrialGift	= 28,		-- 探员试炼礼包购买
	SFT_HeroSummonShop	= 29,		-- 精英召唤礼包购买
	SFT_NoBilityWeekGift = 30,		-- 贵族专享礼包购买
	SFT_GodsPrayShop	= 31,		-- 神灵祈愿礼包购买
	SFT_BoundaryWarOrder = 32, 		-- 临界战令购买
	SFT_ServerGroupBuy  = 33,       -- 全服礼包
	SFT_CollectWordsShop  = 34,     -- 集字活动礼包购买
	SFT_MazeWarOrder		= 35,	-- 迷宫战令购买
	SFT_HeroTrialPreferGift	  = 36,	--探员试炼特惠礼包
	SFT_TourPreferGift 		  = 37,	--巡礼特惠礼包
	SFT_GashaponPreferGift 	  = 38, --扭蛋特惠礼包
	SFT_ShrinePrayPreferGift  = 39, --神社祈福特惠礼包
	SFT_TrialShop             = 40, --阵营试炼礼包购买
	SFT_CorssKingJourney 	  = 41, --跨服王者之征
	SFT_HeroSummonShopDay  	  = 42, --精英召唤每日限时商城
	SFT_EndlessRoadWarOrder		= 43,	-- 迷宫战令购买
	SFT_GodArms 			= 44,	--幻秘武购买
	SFT_HallowWarOrder		= 45,	-- 圣器战令购买
	SFT_HolidayShop                = 46,
	SFT_HeroVoteSale            = 47, --人气探员投票返场购买
	SFT_HeroVoteShop            = 48, --人气探员投票商城
	SFT_WorkTogether            = 49, --协力大作战活动限时商城
	SFT_ActivityGodMarket 		= 50, --神墟宝藏购买
	SFT_SmallElfWarOrder		= 51, --小额精灵执照
	SFT_FashionCharge           = 52, --时装点券充值购买
	SFT_LanternGift				= 53, -- 元宵礼包
	SFT_NewHeroSummonShop		= 54, -- 新英雄召唤活动商城购买
	SFT_NewYearShop				= 55, -- 新年商城购买
	SFT_NewYearShopDay			= 56, -- 新年每日商城购买

}