--这个文件跟testType.dir对应上去id号对应上去，desc 就是按钮，text功能说明　parme1.parme２.parme３都是int parme4是string 备用的
--parme里面的name是对应着编辑框描述，value是默认值
return {
    [1] = {
        desc = "添加资源",
        text = "1经验2金币3物品4卡牌英雄5VIP经验,资源code为1:金币,2钻石",
        parme1 = {name="资源类型", value=4},
        parme2 = {name="资源code", value=15001},
        parme3 = {name="资源数量", value=1},
        parme4 = {name="英雄等级", value=200},
    },
    [2] = {
        desc = "设置推图",
        text = "",
        parme2 = {name="设置城市", value=1},
        parme3 = {name="设置章节", value=1},
        parme4 = {name="设置等级", value=8},
        parme1 = {name="1", value=1},
    },
    [3] = {
        desc = "设置角色属性",
        text = "",
        parme1 = {name="设置等级", value=200},
        parme2 = {name="", value=1},
        parme3 = {name="", value=1},
        parme4 = {name="", value=1},
    },
    [4] = {
        desc = "聊天",
        text = "",
        parme1 = {name="聊天类型", value=1},
        parme2 = {name="接收聊天玩家id", value=""},
        parme3 = {name="", value=1},
        parme4 = {name="内容", value="11111111111"},
    },
    [5] = {
        desc = "统计数据更新",
        text = "统计类型参考RecordType, 数量即达成条件Count, 参数列表依次填p1,p2,p3数值",
        parme1 = {name="统计类型", value=1},
        parme2 = {name="数量", value=""}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="参数列表", value=""},
    },
    [6] = {
        desc = "邮件",
        text = "1添加有道具邮件2添加没有道具的邮件3清空指定邮件4清空所有邮件",
        parme1 = {name="邮件类型", value=1},
        parme2 = {name="道具id", value=10000002}, 
        parme3 = {name="道具数量", value=1}, 
        parme4 = {name="参数列表", value=""},
    },
    [7] = {
        desc = "设置阵容", 
        text = "操作阵容1上阵　2下阵3顶替",
        parme1 = {name="阵容类型", value=1}, 
        parme2 = {name="操作阵容", value=1}, 
        parme3 = {name="上阵位置", value=0}, 
        parme4 = {name="英雄类型uuid", value=""},
    },
    [8] = {
        desc = "好友", 
        text = "1加好友2删除好友3拉入黑名单",
        parme1 = {name="操作类型", value=1}, 
        parme2 = {name="好友id", value=1}, 
        parme3 = {name="", value=0}, 
        parme4 = {name="", value=""},
    },
    [9] = {
        desc = "背包", 
        text = "1清空背包", 
        parme1 = {name="操作类型", value=1}, 
        parme2 = {name="背包类型", value=1}, 
        parme3 = {name="", value=0}, 
        parme4 = {name="", value=""},
    },
    [10] = {
        desc = "加速服务器时间", 
        text = "1 小时 2分钟　3秒 4时间戳", 
        parme1 = {name="操作类型", value=1}, 
        parme2 = {name="秒", value=1}, 
        parme3 = {name="分钟", value=1}, 
        parme4 = {name="小时", value=1},
    },
    [11] = {
        desc = "爬塔", 
        text = "2000普通 2001人族 2002兽族 2004机械", 
        parme1 = {name="操作类型", value=2000}, 
        parme2 = {name="层", value=67}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=1},
    },
    [12] = {
        desc = "迷宫", 
        text = "1移动格子2添加遗物id", 
        parme1 = {name="操作类型", value=1}, 
        parme2 = {name="参数", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=1},
    },
    [13] = {
        desc = "英雄添加技能", 
        text = "(我方1，敌方2)side*100+(前1，后2，替补3)列数*10+行数 (111,112...)(..231,232), 位置不对直接全部置空", 
        parme1 = {name="位置", value=111}, 
        parme2 = {name="", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="技能", value="126,127"},
    },
    [14] = {
        desc = "清除玩法次数", 
        text = "", 
        parme1 = {name="", value=1}, 
        parme2 = {name="", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=1},
    },
    [15] = {
        desc = "公会", 
        text = "1公会活跃, 2公会活跃经验, 3公会经验, 4玩家离线时间戳(不能修改在线或者自己),p2玩家id,p3时间戳 5系统发送物品到公会宝库  6发物品到宝库 param2 code, param3 数量  7 公会宝库清空 8增加公会联赛物品", 
        parme1 = {name="操作类型", value=1}, 
        parme2 = {name="数值", value=1}, 
        parme3 = {name="数值2", value=1}, 
        parme4 = {name="", value=1},
    },
    [16] = {
        desc = "配置检测", 
        text = "检测前端配置表", 
        parme1 = {name="操作类型", value=1}, 
        parme2 = {name="数值", value=1}, 
        parme3 = {name="数值2", value=1}, 
        parme4 = {name="", value=1},
    },
    [17] = {
        desc = "秘境",
        text = "1跳到层和格子(触发事件)  2设置寻宝次数", 
        parme1 ={name="操作类型", value=1}, 
        parme2 = {name="层/次数", value=1}, 
        parme3 = {name="格子", value=1}, 
        parme4 = {name="问题", value=1},
    },
    [18] = {
        desc = "公会个人数据", 
        text = "1.增加占卜手气值, 2.重置占卜数据, 3.设置退会时间(单位秒, 默认0)", 
        parme1 = {name="类型", value=0}, 
        parme2 = {name="数值", value=0}, 
        parme3 = {name="数值2", value=0}, 
        parme4 = {name="", value=""},
    },
    [19] = {
        desc = "英雄添加属性", 
        text = "只是进入战斗加, code为0清除所有属性，属性类型为0， 清除对应code所有属性", 
        parme1 = {name="英雄code", value=1}, 
        parme2 = {name="类型", value=1}, 
        parme3 = {name="数值", value=1}, 
        parme4 = {name="", value=1},
    },
    [20] = {
        desc = "商店", 
        text = "服务端内部测试", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="商店类型", value=1}, 
        parme3 = {name="操作类型", value=1}, 
        parme4 = {name="商店类型", value="test"},
    },  
    [21] = {
        desc = "符文", 
        text = "符文 1加属性 {'1':[1,100],'2':[1,100]} ", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="code", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="属性格式", value="{\"1\":[1,5],\"2\":[2,6]}"},
    },
    [22] = {
        desc = "极地探索", 
        text = "极地探索 命令类型 1 设置 补给值 2关卡设置 关卡数量", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="设置值", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value="test"},
    },
    [23] = {
        desc = "图鉴", 
        text = "图鉴 1类型加收集点2类型加英雄好感度", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="类型", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value="test"},
    },
    [24] = {
        desc = "活动内部调试", 
        text = "活动内部调试　", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="类型", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value="test"},
    },
    [25] = {
        desc = "职级", 
        text = "职级 命令类型 1 升职 2设置职级 参数=职级 3 重置", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="参数", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value="test"},
    },
    [26] = {
        desc = "vip", 
        text = "vip 1 加VIP经验 ", 
        parme1 = {name="命令类型", value=1}, 
        parme2 = {name="类型", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value="test"},
    },
    [27] = {
        desc = "充值", 
        text = "参数1(类型 0充值 其它对应购买类型) 参数2(rmb价格) 参数3(类型0赠送元宝 其它类型购买id)", 
        parme1 = {name="类型", value=0}, 
        parme2 = {name="rmb", value=30}, 
        parme3 = {name="购买id", value=88}, 
        parme4 = {name="", value="test"},
    },
    [28] = {
        desc = "抽卡测试", 
        text = "", 
        parme1 = {name="抽奖id", value=9}, 
        parme2 = {name="", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=""},
    },
    [29] = {
        desc = "秘武", 
        text = "秘武:类型1 激活1并且加入到方案1中 2 秘武过期 参数1 对应秘武id", 
        parme1 = {name="类型",value = 1}, 
        parme2 = {name="参数1", value=10}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=""},
    },
    [30] = {
        desc = "晨星会所测试", 
        text = "",
        parme1 = {name="类型", value=1}, 
        parme2 = {name="", value=1}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=""},
    },
    [31] = {
        desc = "高阶竞技场", 
        text = "类型1增加积分 参数为数值",
        parme1 = {name="类型", value=1}, 
        parme2 = {name="参数", value=100}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=""},
    },
    [32] = {
        desc = "普通竞技场", 
        text = "类型1增加积分 参数为数值",
        parme1 = {name="类型", value=1}, 
        parme2 = {name="参数", value=100}, 
        parme3 = {name="", value=1}, 
        parme4 = {name="", value=""},
    },
    [33] = {
        desc = "世界擂台赛", 
        text = "类型 - 1.重开本轮比赛, 2.执行到下一阶段, 3.结算本轮活动",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="", value=0 },
        parme3 = {name="", value=0 },
        parme4 = {name="", value="" },
    },
    [34] = {
        desc = "次元裂缝", 
        text = "类型 - 1重置自己本轮数据, 2开启下轮活动",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数1", value=0 }, 
        parme3 = {name="参数2", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [35] = {
        desc = "精灵", 
        text = "类型 1 添加精灵,2添加精灵经验,3,指定精灵星数",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="id ", value=0 }, 
        parme3 = {name="数量", value=0 }, 
        parme4 = {name="uuid", value="" },
    },
    [36] = {
        desc = "查询卡片战力信息", 
        text = "类型 1.查询某code卡牌, 2.指定查询卡牌",
        parme1 = {name="code类型", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="uuid", value="" },
    },
     [37] = {
        desc = "幻境", 
        text = "类型 1 单人模式 2 全体模式 选择唯一id 每跳一关加12",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数1", value=12 }, 
        parme3 = {name="参数2", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [38] = {
        desc = "功能开启", 
        text = "模块类型 1 条件类型 2 条件值 3",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数1", value=1 }, 
        parme3 = {name="参数2", value=0 }, 
        parme4 = {name="参数列表", value="test" },
    },
    [39] = {
        desc = "保存服务器时间", 
        text = "类型 1保存(重启也以这个时间点继续) 2清除",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [40] = {
        desc = "修改开服时间", 
        text = "当前+-多少天(需要重启)",
        parme1 = {name="值", value=0 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [41] = {
        desc = "圣器", 
        text = "模块类型 1 加点  5 直接结算",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="值", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [42] = {
        desc = "临界", 
        text = "模块类型 ",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="值", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [42] = {
        desc = "临界", 
        text = "模块类型 ",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="值", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [43] = {
        desc = "清除英雄", 
        text = "",
        parme1 = {name="", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [44] = {
        desc = "跨天", 
        text = "",
        parme1 = {name="", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [45] = {
        desc = "天境赛擂台赛", 
        text = "类型 - 1.重开本轮比赛, 2.执行到下一阶段, 3.结算本轮活动",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [46] = {
        desc = "天域赛", 
        text = "类型 -- 1结算 2重开",
        parme1 = {name="", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [47] = {
        desc = "梦境pvp", 
        text = "类型 -- 1开始 2触发64名 3开始准备阶段 4清空关闭所有数据 这个命令必须开启 活动",
        parme1 = {name="", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [48] = {
        desc = "跨天5点", 
        text = "",
        parme1 = {name="", value=1 }, 
        parme2 = {name="", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [49] = {
        desc = "弹幕", 
        text = "1发送弹幕 2获取弹幕",
        parme1 = {name="", value=1 }, 
        parme2 = {name="", value=1 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="test msg Barrage 0 1 " },
    },
     [50] = {
        desc = "神殿", 
        text = "1调整强化",
        parme1 = {name="命令的类型", value=1 }, 
        parme2 = {name="选择的位置", value=1 }, 
        parme3 = {name="强化的等级", value=1 }, 
        parme4 = {name="", value="StarTemple" },
    },
    [51] = {
        desc = "公会联赛", 
        text = "类型1 开启(执行后需等待30秒开启，存在跨服分配过程), 类型2 赛季结算",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数", value=0 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [52] = {
        desc = "跨服竞技场", 
        text = "类型1 加积分； 类型2 发放未领取的今日奖励； 类型3 重置玩家个人数据",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="玩家id", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [53] = {
        desc = "每日登录活动(类型:86)", 
        text = "类型1 领取奖励； 类型2 增加已登录天数； 类型3 重置自己活动数据； 类型4 发放未领取奖励",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数(奖励id或天数)", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [54] = {
        desc = "英雄合成打印", 
        text = "",
        parme1 = {name="碎片id", value=40000013 }, 
        parme2 = {name="次数", value=1000 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [55] = {
        desc = "传奇赛", 
        text = "1开始",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数", value=1 }, 
        parme3 = {name="", value=0 }, 
        parme4 = {name="", value="" },
    },
    [56] = {
        desc = "巅峰竞技", 
        text = "类型1 重置玩家每日数据; 类型2000 按天往后切换本赛季状态(参数为第X天)",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="玩家id 或 参数", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [57] = {
        desc = "跨服天梯赛", 
        text = "类型1 开活动; 类型2 关活动",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="玩家id 或 参数", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [58] = {
        desc = "跨服超凡赛", 
        text = "类型1 添加分数 类型2 重开",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="玩家id", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [59] = {
        desc = "跨服天梯冠军赛", 
        text = "类型1 开活动; 类型2 关活动",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="玩家id 或 参数", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [60] = {
        desc = "事件播报", 
        text = "类型1 立即播报; 类型2 删除播报",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="事件id", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [61] = {
        desc = "协力大作战", 
        text = "类型1、2、3 按{组id,关卡id}添加积分和占领度; 类型4 增加助力值; 类型5 重置玩家活动数据; 类型6 重置助力值",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数或组id", value=0 }, 
        parme3 = {name="参数或关卡id", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
      [62] = {
        desc = "异能计划", 
        text = "类型1 跳关 参数1 增加多少关; 类型2 重置次数 类型3 增加boss破点 类型4 直接结算 类型6 重置数据",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数1", value=1 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [63] = {
        desc = "节日寄语", 
        text = "类型1 重置玩家活动数据",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
    [64] = {
        desc = "周巡拼图", 
        text = "类型1 重置玩家活动数据",
        parme1 = {name="类型", value=1 }, 
        parme2 = {name="参数", value=0 }, 
        parme3 = {name="参数", value=0 }, 
        parme4 = {name="参数列表", value="" },
    },
}