--Name : PushMapChpterpassView.lua
--Author : generated by FairyGUI
--Date : 2020-7-17
--Desc :

local PushMapChpterpassView, Super = class("PushMapChpterpassView", Window)

function PushMapChpterpassView:ctor()
    --LuaLog("PushMapChpterpassView ctor")
    self._packName = "PushMap"
    self._compName = "PushMapChpterpassView"
    self._rootDepth = LayerDepth.FaceWindow
end

function PushMapChpterpassView:_initUI()
    self.btn_close1=self.view:getChild("btn_close1")
	local c1 = self.view:getController("c1")
	c1:setSelectedIndex(self._args.ctr)
end

function PushMapChpterpassView:_initEvent()
    self.btn_close1:addClickListener(function(...)
        self:closeView()
        end)
end

return PushMapChpterpassView
