--Date :2021-01-18
--Author : generated by FairyGUI
--Desc :

local CooperationRewardView, Super = class("CooperationRewardView", Window)

function CooperationRewardView:ctor()
    --LuaLog("CooperationRewardView ctor")
    self._packName = "CooperationActivities"
    self._compName = "CooperationRewardView"
    self._rootDepth = LayerDepth.PopWindow
end

function CooperationRewardView:_initEvent()
end

function CooperationRewardView:_initVM()
    local viewNode = self.view
    ---Do not modify following code--------
    --{autoFields}:CooperationActivities.CooperationRewardView
	self.blackBg = viewNode:getChildAutoType('blackBg')--GButton
	self.c1 = viewNode:getController('c1')--Controller
	self.frame = viewNode:getChildAutoType('frame')--GLabel
	self.list_rank = viewNode:getChildAutoType('list_rank')--GList
	self.list_type = viewNode:getChildAutoType('list_type')--GList
	self.list_zhenya = viewNode:getChildAutoType('list_zhenya')--GList
 --{autoFieldsEnd}:CooperationActivities.CooperationRewardView
    --Do not modify above code-------------
end

function CooperationRewardView:_initListener()
    self.blackBg:addClickListener(
        function()
        end
    )

    self.list_type:setItemRenderer(
        function(index, obj)
        end
    )
end

function CooperationRewardView:_initUI()
    self:_initVM()
    self:_initListener()
    self.list_type:setItemRenderer(
        function(index, obj)
            local title = obj:getChildAutoType("title")
            if index == 0 then
                self:showRankList()
                obj:setSelected(true)
                self.c1:setSelectedIndex(0)
                title:setText("排名奖励")
            else
                title:setText("占领奖励")
            end
            obj:removeClickListener(100)
            --池子里面原来的事件注销掉
            obj:addClickListener(
                function(context)
                    if index == 0 then
                        self:showRankList()
                        self.c1:setSelectedIndex(0)
                    else
                        self:showBossList()
                        self.c1:setSelectedIndex(1)
                    end
                end,
                100
            )
        end
    )
    self.list_type:setNumItems(2)
end

function CooperationRewardView:showRankList()
    local groupId = CooperationActivitiesModel:getActModuleId(GameDef.ActivityType.WorkTogetherAct)
    local configInfo = DynamicConfigData.t_CooperationRankAward
    local arr = configInfo[groupId]
    self.list_rank:setItemRenderer(
        function(index, obj)
            local itemMode = arr[index + 1]
            local c1 = obj:getController("c1")
            if itemMode.min==itemMode.max then
                if index + 1 <= 3 then
                    c1:setSelectedIndex(index)
                else
                    c1:setSelectedIndex(3)
                end
            else
                c1:setSelectedIndex(3)
            end
            local txt_order = obj:getChildAutoType("txt_order")
            txt_order:setText(string.format("%s-%s", itemMode.min, itemMode.max))
            local list_prop = obj:getChildAutoType("list_prop")
            list_prop:setItemRenderer(
                function(rewardId, rewardobj)
                    local itemcell1 = BindManager.bindItemCell(rewardobj)
                    local award = itemMode.award[rewardId + 1]
                    itemcell1:setData(award.code, award.amount, award.type)
                end
            )
            list_prop:setNumItems(#itemMode.award)
        end
    )
    self.list_rank:setNumItems(#arr)
end

function CooperationRewardView:showBossList()
    local groupId = CooperationActivitiesModel:getActModuleId(GameDef.ActivityType.WorkTogetherAct)
    local configInfo = DynamicConfigData.t_CooperationBoss
    local arr = configInfo[groupId]
    self.list_zhenya:setItemRenderer(
        function(index, obj)
            local itemMode = arr[index + 1]
            local txt_desc = obj:getChildAutoType("txt_desc")
            local heroInfo = DynamicConfigData.t_hero[itemMode.show]
            txt_desc:setText(string.format("完全镇压%s", ColorUtil.formatColorString1(heroInfo.heroName, "#ca5600")))
            local list_prop = obj:getChildAutoType("list_prop")
            list_prop:setItemRenderer(
                function(rewardId, rewardobj)
                    local itemcell1 = BindManager.bindItemCell(rewardobj)
                    local award = itemMode.awrad[rewardId + 1]
                    itemcell1:setData(award.code, award.amount, award.type)
                end
            )
            list_prop:setNumItems(#itemMode.awrad)
        end
    )
    self.list_zhenya:setNumItems(#arr)
end

return CooperationRewardView
