--Name : FilmController.lua
--Author : generated by FairyGUI
--Date : 2020-4-18
--Desc : 

local FilmController = class("FilmController",Controller)

function FilmController:init()
	
end

return FilmController