--Name : AccumulatedAddMoneyView1.lua
--Author : generated by FairyGUI
--Date : 2020-7-8
--Desc : --累计充值豪礼  7日累充

local AccumulatedAddMoneyView1, Super = class("AccumulatedAddMoneyView1", Window)
local ItemConfiger = require "Game.ConfigReaders.ItemConfiger"
function AccumulatedAddMoneyView1:ctor()
    LuaLog("AccumulatedAddMoneyView1 ctor")
    self._packName = "OperatingActivities"
    self._compName = "AccumulatedAddMoneyView"
	--这里不能根据moduleId判断（策划说奖励是后台配的），元旦先临时换另外一个ui
	--self._packName = "AccumulatedAddMoney"    
    --self._compName = "AccumulatedAddMoneyView12"
    --self._rootDepth = LayerDepth.Window
    self.viewIndexTag = GameDef.ActivityType.FestivalRecharge
    self.starInfo = false
    self.bannerUrl = false
end

function AccumulatedAddMoneyView1:_initEvent()
end

function AccumulatedAddMoneyView1:_initVM()
    local vmRoot = self
    local viewNode = self.view
    ---Do not modify following code--------
    --{vmFields}:OperatingActivities.AccumulatedAddMoneyView1
    	vmRoot.list_item = viewNode:getChildAutoType("$list_item")--list
    	vmRoot.ltxt_countDown = viewNode:getChildAutoType("$ltxt_countDown")--text
    	vmRoot.img_banner = viewNode:getChildAutoType("$img_banner")--loader
    --{vmFieldsEnd}:OperatingActivities.AccumulatedAddMoneyView1
    --Do not modify above code-------------
end

function AccumulatedAddMoneyView1:setActType(_args)
 --   printTable(21, "累计充值打印的数据111111", _args)
end

function AccumulatedAddMoneyView1:_initUI()
    self:_initVM()
  --  printTable(21, "累计充值打印的数据", self._args)
    self:showView()
end

function AccumulatedAddMoneyView1:showCountTime()
    local actData = ModelManager.ActivityModel:getActityByType(self.viewIndexTag)
    if not actData then
        return
    end
    local actId = actData.id
    local status, addtime = ModelManager.ActivityModel:getActStatusAndLastTime(actId)
    if not addtime then
        return
    end
    if status == 2 and addtime == -1 then
        self.ltxt_countDown:setText(Desc.activity_txt5)
    else
        local lastTime = addtime / 1000
        if lastTime == -1 then
            self.ltxt_countDown:setText(Desc.activity_txt5)
        else
            if not tolua.isnull(self.ltxt_countDown) then
                self.ltxt_countDown:setText(TimeLib.GetTimeFormatDay(lastTime, 2))
             --TimeLib.formatTime(addtime,true,false)
            end
            local function onCountDown(time)
                if not tolua.isnull(self.ltxt_countDown) then
                    self.ltxt_countDown:setText(TimeLib.GetTimeFormatDay(time, 2))
                 --TimeLib.formatTime(time,true,false)
                end
            end
            local function onEnd(...)
                if not tolua.isnull(self.ltxt_countDown) then
                 self.ltxt_countDown:setText(Desc.activity_txt4)
                end
            end
            if self.calltimer then
                TimeLib.clearCountDown(self.calltimer)
            end
            self.calltimer = TimeLib.newCountDown(lastTime, onCountDown, onEnd, false, false, false)
        end
    end
end

function AccumulatedAddMoneyView1:showView()
    self.starInfo, self.bannerUrl = OperatingActivitiesModel:getAccumulatedAddInfo(self.viewIndexTag, true)
    self.img_banner:setURL(string.format("%s%s", "UI/activity/", self.bannerUrl))
    self:showCountTime()
    self.list_item:setVirtual()
    self.list_item:setItemRenderer(
        function(index, obj)
            local money = OperatingActivitiesModel:getAccumulatedAddMoney(self.viewIndexTag)
            local starInfo = self.starInfo
            local itemInfo = starInfo[index + 1]
			obj:getChild("$txt_desc"):setText(Desc.activity_txt6..ColorUtil.formatColorString1(itemInfo.accType,"#0ea41d")..Desc.activity_txt7)
            --local iconUrl = ItemConfiger.getItemIconByCodeAndType(2, 2)
            --obj:getChild("$img_num"):setURL(iconUrl)
            obj:getChild("$txt_num"):setText(money.. "/" .. itemInfo.accType)
            local ctrl = obj:getController("c1")
            local lingqu = OperatingActivitiesModel:getAccumulatedAddLingqu(self.viewIndexTag, itemInfo.id)
            local red = false
            local state = 0
            if money < itemInfo.accType then --无法领取
                state = 1
                ctrl:setSelectedIndex(1)
                red = false
            elseif money >= itemInfo.accType and lingqu == false then --可领取
                state = 2
                ctrl:setSelectedIndex(0)
                red = true
            elseif money >= itemInfo.accType and lingqu == true then --已领取
                state = 3
                ctrl:setSelectedIndex(2)
                red = false
			end
			local btn = obj:getChild("$btn_get")
            local img_red =btn:getChild("img_red")
            img_red:setVisible(red)
            local list_prop = obj:getChild("$list_prop")
            list_prop:setItemRenderer(
                function(idx2, obj2)
                    local itemcell = BindManager.bindItemCell(obj2)
                    local award = itemInfo.reward[idx2 + 1]
                    itemcell:setData(award.code, award.amount, award.type)
                    itemcell:setIsHook(state == 3)
                end
            )
            list_prop:setNumItems(#itemInfo.reward)
            -- 领取按钮
         
            btn:removeClickListener(100)
            btn:addClickListener(
                function()
                    OperatingActivitiesModel:AccChargeRecieveReward(itemInfo.id)
                end,
                100
            )
            -- 前往按钮
            local enterbtn = obj:getChild("$btn_enter")
            enterbtn:removeClickListener(100)
            enterbtn:addClickListener(
                function()
                    --ModuleUtil.openModule(ModuleId.DailyGiftBag, true)
                    ModuleUtil.openModule(ModuleId.Recharge.id)
                end,
                100
            )
        end
    )
    self.list_item:setNumItems(#self.starInfo)
end

function AccumulatedAddMoneyView1:activity_AccumulatedAddInfoupdate(...)
	self.starInfo, self.bannerUrl = OperatingActivitiesModel:getAccumulatedAddInfo(self.viewIndexTag, true)
	self.list_item:setNumItems(#self.starInfo);
end
	

return AccumulatedAddMoneyView1
