--Name : HeroBossActivityController.lua
--Author : generated by FairyGUI
--Date : 2020-5-28
--Desc : 

local HeroBossActivityController = class("HeroBossActivityController",Controller)

function HeroBossActivityController:init()
	
end


return HeroBossActivityController