--Date :2020-12-04
--Author : generated by FairyGUI
--Desc : 

local TimingPushController = class("TimingPush",Controller)

function TimingPushController:init()
	
end
function TimingPushController:GamePlay_UpdateData (_,params)
    if params.gamePlayType == GameDef.GamePlayType.TimePush then
		TimingPushModel:setSeverData(params.gp)
    end
end
function TimingPushController:view_change(name)
	TimingPushModel:changeView(name)
end

function TimingPushController:serverTime_crossDay(name)
	TimingPushModel:changeView(name)
end
return TimingPushController