--Date :2021-01-27
--Author : generated by FairyGUI
--Desc : 

local SurveyQuestionController = class("SurveyQuestion",Controller)

function SurveyQuestionController:init()
end


function SurveyQuestionController:Activity_UpdateData(_, param)
	if param.type == GameDef.ActivityType.Survey then
		printTable(5656,"问卷调查",param)
		SurveyQuestionModel:initData(param)
	end
end

return SurveyQuestionController