--Date :2021-01-13
--Author : generated by FairyGUI
--Desc : 

local FashionPreBattleView,Super = class("FashionPreBattleView", View)
local HeroItem = require "Game.Modules.Battle.Cell.HeroItem"
local CameraController = require "Game.Modules.Battle.Effect.CameraController"
local SkillConfiger = require "Game.ConfigReaders.SkillConfiger"

function FashionPreBattleView:ctor()
	--LuaLog("FashionPreBattleView ctor")
	self._packName = "Fashion"
	self._compName = "FashionPreBattleView"
	--self._rootDepth = LayerDepth.Window
	
end

function FashionPreBattleView:_initVM( )
	local viewNode = self.view
	---Do not modify following code--------
	--{autoFields}:Fashion.FashionPreBattleView
	self.CameraView = viewNode:getChildAutoType('CameraView')--CameraView
	self.CameraView.arrayCenter = viewNode:getChildAutoType('CameraView/arrayCenter')--GGraph
	self.CameraView.centerPoint = viewNode:getChildAutoType('CameraView/centerPoint')--GGraph
	self.CameraView.enemyCenter = viewNode:getChildAutoType('CameraView/enemyCenter')--GGraph
	self.CameraView.playerCenter = viewNode:getChildAutoType('CameraView/playerCenter')--GGraph
	self.CameraView.skillPos = viewNode:getChildAutoType('CameraView/skillPos')--GGroup
	self.enemy = viewNode:getChildAutoType('enemy')--GButton
	self.hero = viewNode:getChildAutoType('hero')--GButton
	self.lihuiMask = viewNode:getChildAutoType('lihuiMask')--lihuiMask
	--{autoFieldsEnd}:Fashion.FashionPreBattleView
	--Do not modify above code-------------
end

function FashionPreBattleView:_initUI( )
	self:_initVM()
	CameraController.setScreenView(self.view,self.view)
    BattleManager:beginGame()
	BattleModel:setMapPoint({
      center = self.CameraView.centerPoint,
      enemyCenter = self.CameraView.enemyCenter,
      playerCenter = self.CameraView.playerCenter,
      arrayCenter = self.CameraView.arrayCenter,
      --allHurtTip=allHurtTip
 	 })
	self.skillIdList = self._args.skillId
    self.data = self._args.data
    self.fashionId = self._args.fashionId
    self:setMySquad()
    self:setOtherSquad()
end

-- 创建角色
function FashionPreBattleView:setMySquad()
	self.view:getChildAutoType("hero"):setSortingOrder(11)
	self.hero = BattleModel:creatFightItem(122,self.data.heroCode,self.fashionId,self.view:getChildAutoType("hero"))  
    self.hero.view:setTouchable(false)
    self.hero:setHideBarGroup(true)
end

-- 设置敌方阵容
function FashionPreBattleView:setOtherSquad()
	self.view:getChildAutoType("enemy"):setSortingOrder(11)
    self.enemy = BattleModel:creatFightItem(211,self.data.enemyTroop,nil,self.view:getChildAutoType("enemy")) 
    self.enemy.view:setTouchable(false)
    self.enemy:setHideBarGroup(true)
end

function FashionPreBattleView:FashionPreView_PlaySkill(_,data)
    local skillId = data.skillId
    local skillInfo = SkillConfiger.getSkillById(skillId)
    local activeSkill = DynamicConfigData.t_activeSkill[skillInfo.activeSkill[1]]
    local targetId = 211
    if skillId == 1500321 then 
        targetId = 122
    end
    local fightObjData = BattleModel:creatSkillData(122,targetId,skillId)
    SkillManager.playSkill(122,targetId,fightObjData,function ()
        Dispatcher.dispatchEvent(EventType.FashionPreView_EndSkill)
    end)
end

function FashionPreBattleView:_exit()
end

return FashionPreBattleView